# Generated by Django 5.0.1 on 2026-02-05 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_alter_extractioncommitsnapshot_committed_by'),
        ('projects', '0004_add_rbac_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicColumnDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(help_text="Target table: 'multifamily_unit', 'land_parcel', etc.", max_length=100)),
                ('column_key', models.CharField(help_text="Internal key, e.g., 'delinquent_rent', 'section_8'", max_length=100)),
                ('display_label', models.CharField(help_text="User-facing label, e.g., 'Delinquent Rent', 'Section 8'", max_length=100)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('currency', 'Currency'), ('percent', 'Percentage'), ('boolean', 'Yes/No'), ('date', 'Date')], default='text', max_length=20)),
                ('format_pattern', models.CharField(blank=True, help_text="Format pattern, e.g., '$#,##0.00' for currency", max_length=50, null=True)),
                ('source', models.CharField(choices=[('user', 'User Created'), ('landscaper', 'Landscaper Proposed'), ('extraction', 'Auto-Extracted')], default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_proposed', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dynamic_columns', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_columns', to='projects.project')),
                ('proposed_from_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_columns', to='documents.document')),
            ],
            options={
                'verbose_name': 'Dynamic Column Definition',
                'verbose_name_plural': 'Dynamic Column Definitions',
                'db_table': 'landscape"."tbl_dynamic_column_definition',
                'ordering': ['display_order', 'created_at'],
                'unique_together': {('project', 'table_name', 'column_key')},
            },
        ),
        migrations.CreateModel(
            name='DynamicColumnValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField(help_text='ID of the row in the target table (e.g., unit_id)')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='dynamic.dynamiccolumndefinition')),
                ('extracted_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_dynamic_values', to='documents.document')),
            ],
            options={
                'verbose_name': 'Dynamic Column Value',
                'verbose_name_plural': 'Dynamic Column Values',
                'db_table': 'landscape"."tbl_dynamic_column_value',
                'indexes': [models.Index(fields=['column_definition', 'row_id'], name='tbl_dynamic_column__134554_idx'), models.Index(fields=['row_id'], name='tbl_dynamic_row_id_9def5e_idx')],
                'unique_together': {('column_definition', 'row_id')},
            },
        ),
    ]
