# Generated by Django 5.0.1 on 2025-10-23 04:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupFamily',
            fields=[
                ('family_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('ord', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'db_table': 'lu_family',
                'ordering': ['ord', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LookupSubtype',
            fields=[
                ('subtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('ord', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property Subtype',
                'verbose_name_plural': 'Property Subtypes',
                'db_table': 'lu_subtype',
                'ordering': ['ord', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LookupType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('ord', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Property Type',
                'verbose_name_plural': 'Property Types',
                'db_table': 'lu_type',
                'ordering': ['ord', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('acres_gross', models.FloatField(blank=True, null=True)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lon', models.FloatField(blank=True, null=True)),
                ('location_description', models.TextField(blank=True, null=True)),
                ('project_address', models.TextField(blank=True, null=True)),
                ('jurisdiction_city', models.CharField(blank=True, max_length=100, null=True)),
                ('jurisdiction_county', models.CharField(blank=True, max_length=100, null=True)),
                ('jurisdiction_state', models.CharField(blank=True, max_length=10, null=True)),
                ('jurisdiction_integrated', models.BooleanField(blank=True, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('development_type', models.CharField(blank=True, max_length=100, null=True)),
                ('project_type', models.CharField(blank=True, max_length=50, null=True)),
                ('property_type_code', models.CharField(blank=True, max_length=50, null=True)),
                ('financial_model_type', models.CharField(blank=True, max_length=50, null=True)),
                ('uses_global_taxonomy', models.BooleanField(blank=True, null=True)),
                ('taxonomy_customized', models.BooleanField(blank=True, null=True)),
                ('target_units', models.IntegerField(blank=True, null=True)),
                ('price_range_low', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('price_range_high', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('legal_owner', models.TextField(blank=True, null=True)),
                ('developer_owner', models.TextField(blank=True, null=True)),
                ('existing_land_use', models.TextField(blank=True, null=True)),
                ('assessed_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('analysis_start_date', models.DateField(blank=True, null=True)),
                ('analysis_end_date', models.DateField(blank=True, null=True)),
                ('calculation_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('discount_rate_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('cost_of_capital_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('gis_metadata', models.JSONField(blank=True, null=True)),
                ('ai_last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('schema_version', models.IntegerField(blank=True, null=True)),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('template_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'tbl_project',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyTypeConfig',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_type', models.CharField(max_length=50, unique=True)),
                ('tab_label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_columns', models.JSONField()),
                ('import_suggestions', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property Type Config',
                'verbose_name_plural': 'Property Type Configs',
                'db_table': 'tbl_property_type_config',
                'ordering': ['property_type'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(default='user', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('preferences', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
