# Generated by Django 5.0.1 on 2025-11-20 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_key', models.CharField(db_index=True, max_length=255)),
                ('preference_value', models.JSONField(default=dict)),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('project', 'Project'), ('organization', 'Organization')], db_index=True, default='global', max_length=50)),
                ('scope_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'landscape"."tbl_user_preference',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'scope_type', 'scope_id'], name='tbl_user_pr_user_id_c4e8f5_idx'), models.Index(fields=['preference_key'], name='tbl_user_pr_prefere_c180c6_idx'), models.Index(fields=['-updated_at'], name='tbl_user_pr_updated_4533b0_idx')],
                'unique_together': {('user', 'preference_key', 'scope_type', 'scope_id')},
            },
        ),
    ]
