# Generated by Django 4.2.25 on 2025-11-24 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_vendor_contact_id'),
        ('projects', '0002_userpreference'),
    ]

    operations = [
    ]
