# Generated by Django 5.0.1 on 2026-01-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_merge_0002_add_vendor_contact_id_0002_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='demo_projects_provisioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('alpha_tester', 'Alpha Tester')], default='alpha_tester', max_length=50),
        ),
    ]
