# Generated by Django 5.0.1 on 2026-02-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_taxonomy_perspective_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTypeConfig',
            fields=[
                ('config_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(max_length=50)),
                ('analysis_perspective', models.CharField(blank=True, max_length=50, null=True)),
                ('analysis_purpose', models.CharField(blank=True, max_length=50, null=True)),
                ('tile_valuation', models.BooleanField(default=False, help_text='Show Valuation tile (3 approaches)')),
                ('tile_capitalization', models.BooleanField(default=False, help_text='Show Capitalization tile')),
                ('tile_returns', models.BooleanField(default=False, help_text='Show Returns tile')),
                ('tile_development_budget', models.BooleanField(default=False, help_text='Show Dev Budget tile')),
                ('requires_capital_stack', models.BooleanField(default=False)),
                ('requires_comparable_sales', models.BooleanField(default=False)),
                ('requires_income_approach', models.BooleanField(default=False)),
                ('requires_cost_approach', models.BooleanField(default=False)),
                ('available_reports', models.JSONField(blank=True, default=list)),
                ('landscaper_context', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analysis Type Config',
                'verbose_name_plural': 'Analysis Type Configs',
                'db_table': 'tbl_analysis_type_config',
                'managed': False,
            },
        ),
        # NOTE: AlterModelTable ops removed — tables already use
        # landscape schema via db_table = 'landscape"."...' in models.
        # PostgreSQL ALTER TABLE RENAME doesn't support schema-quoted names.
    ]
