# Generated by Django 5.0.1 on 2026-02-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_analysis_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Stored for alpha admin visibility only.', max_length=128, null=True),
        ),
    ]
