# Generated by Django 5.0.1 on 2025-11-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user_id', models.IntegerField(help_text='User ID (currently simplified, would link to auth user)', primary_key=True, serialize=False)),
                ('tier_level', models.CharField(choices=[('analyst', 'Analyst'), ('pro', 'Pro')], default='analyst', help_text='User tier level - controls access to Pro features like Capitalization modeling', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
                'db_table': 'landscape"."user_settings',
            },
        ),
    ]
