# Generated by Django 5.0.1 on 2026-02-03 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLandscaperProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('survey_completed_at', models.DateTimeField(blank=True, null=True)),
                ('role_primary', models.CharField(blank=True, max_length=50, null=True)),
                ('role_property_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_proficiency', models.CharField(blank=True, max_length=50, null=True)),
                ('communication_tone', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_tool', models.CharField(blank=True, max_length=50, null=True)),
                ('markets_text', models.TextField(blank=True, null=True)),
                ('compiled_instructions', models.TextField(blank=True, null=True)),
                ('onboarding_chat_history', models.JSONField(default=list)),
                ('interaction_insights', models.JSONField(default=dict)),
                ('document_insights', models.JSONField(default=dict)),
                ('tos_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='landscaper_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'landscape"."tbl_user_landscaper_profile',
                'ordering': ['-updated_at'],
            },
        ),
    ]
