# Generated by Django 5.0.1 on 2026-02-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userlandscaperprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlandscaperprofile',
            name='custom_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
