# Generated by Django 5.0.1 on 2026-03-08 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_custom_instructions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGridPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.BigIntegerField(help_text='FK to tbl_project.project_id')),
                ('grid_id', models.CharField(help_text="Grid identifier, e.g. 'rent_roll', 'budget'", max_length=50)),
                ('column_order', models.JSONField(default=list, help_text='Ordered list of column IDs, e.g. ["unitNumber","bedrooms",...]')),
                ('column_visibility', models.JSONField(default=dict, help_text='Column ID → boolean, e.g. {"unitNumber": true, "notes": false}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='grid_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Grid Preference',
                'verbose_name_plural': 'User Grid Preferences',
                'db_table': 'landscape"."tbl_user_grid_preference',
                'unique_together': {('user', 'project_id', 'grid_id')},
            },
        ),
    ]
