-- 20260820_apply_pending_2026.down.sql
-- Reverses 20260820_apply_pending_2026.up.sql.
--
-- NOTE ON THE INDEX DE-DUPLICATION: the up file DROPs 11 duplicate indexes that
-- backend/migrations/046_drop_duplicate_indexes.sql identified. Those drops are
-- NOT reversed here - recreating a duplicate index is not a state anyone wants
-- to return to, and 046 remains in the repo if it is ever needed.
SET search_path TO landscape, public;

DROP TRIGGER IF EXISTS trg_assumption_history_updated ON landscape.tbl_assumption_history;
DROP TRIGGER IF EXISTS trg_user_comparables_updated ON landscape.tbl_user_comparables;
DROP FUNCTION IF EXISTS landscape.update_user_knowledge_timestamp();
ALTER TABLE landscape.landscaper_advice DROP COLUMN IF EXISTS thread_id;
DROP INDEX IF EXISTS landscape.idx_core_doc__parcel_id;
DROP INDEX IF EXISTS landscape.idx_gis_plan_parcel__parcel_id;
DROP INDEX IF EXISTS landscape.idx_tbl_acreage_allocation__parcel_id;
DROP INDEX IF EXISTS landscape.idx_ai_ingestion_history__project_id;
DROP INDEX IF EXISTS landscape.idx_core_doc__parcel_id;
DROP INDEX IF EXISTS landscape.idx_core_doc__parent_doc_id;
DROP INDEX IF EXISTS landscape.idx_core_doc__phase_id;
DROP INDEX IF EXISTS landscape.idx_core_doc_folder__parent_id;
DROP INDEX IF EXISTS landscape.idx_core_fin_budget_version__project_id;
DROP INDEX IF EXISTS landscape.idx_core_fin_category_uom__uom_code;
DROP INDEX IF EXISTS landscape.idx_core_fin_fact_actual__project_id;
DROP INDEX IF EXISTS landscape.idx_core_fin_fact_actual__uom_code;
DROP INDEX IF EXISTS landscape.idx_core_fin_fact_budget__curve_id;
DROP INDEX IF EXISTS landscape.idx_core_fin_fact_budget__growth_rate_set_id;
DROP INDEX IF EXISTS landscape.idx_core_fin_fact_budget__uom_code;
DROP INDEX IF EXISTS landscape.idx_core_unit_cost_item__created_from_project_id;
DROP INDEX IF EXISTS landscape.idx_core_unit_cost_item__default_uom_code;
DROP INDEX IF EXISTS landscape.idx_dms_profile_audit__doc_id;
DROP INDEX IF EXISTS landscape.idx_dms_template_attributes__attr_id;
DROP INDEX IF EXISTS landscape.idx_dms_templates__project_id;
DROP INDEX IF EXISTS landscape.idx_dms_templates__workspace_id;
DROP INDEX IF EXISTS landscape.idx_gis_plan_parcel__parcel_id;
DROP INDEX IF EXISTS landscape.idx_market_competitive_project_products__product_id;
DROP INDEX IF EXISTS landscape.idx_project_jurisdiction_mapping__density_code;
DROP INDEX IF EXISTS landscape.idx_project_jurisdiction_mapping__glossary_id;
DROP INDEX IF EXISTS landscape.idx_project_jurisdiction_mapping__project_id;
DROP INDEX IF EXISTS landscape.idx_tbl_absorption_schedule__area_id;
DROP INDEX IF EXISTS landscape.idx_tbl_acquisition__measure_id;
DROP INDEX IF EXISTS landscape.idx_tbl_acreage_allocation__allocation_type_id;
DROP INDEX IF EXISTS landscape.idx_tbl_acreage_allocation__parcel_id;
DROP INDEX IF EXISTS landscape.idx_tbl_acreage_allocation__phase_id;
DROP INDEX IF EXISTS landscape.idx_tbl_acreage_allocation__source_doc_id;
DROP INDEX IF EXISTS landscape.idx_tbl_approval__project_id;
DROP INDEX IF EXISTS landscape.idx_tbl_benchmark_ai_suggestions__created_benchmark_id;
DROP INDEX IF EXISTS landscape.idx_tbl_benchmark_ai_suggestions__existing_benchmark_id;
DROP INDEX IF EXISTS landscape.idx_tbl_benchmark_ai_suggestions__project_id;
DROP INDEX IF EXISTS landscape.idx_tbl_budget__devphase_id;
DROP INDEX IF EXISTS landscape.idx_tbl_budget__measure_id;
DROP INDEX IF EXISTS landscape.idx_tbl_budget_fact__phase_id;
DROP INDEX IF EXISTS landscape.idx_tbl_budget_fact__source_doc_id;
DROP INDEX IF EXISTS landscape.idx_tbl_budget_items__actual_period_id;
DROP INDEX IF EXISTS landscape.idx_tbl_budget_structure__measure_id;
DROP INDEX IF EXISTS landscape.idx_tbl_capital_call__period_id;
DROP INDEX IF EXISTS landscape.idx_tbl_capitalization__project_id;
DROP INDEX IF EXISTS landscape.idx_tbl_cashflow__lot_id;
DROP INDEX IF EXISTS landscape.idx_tbl_equity_structure__project_id;
DROP INDEX IF EXISTS landscape.idx_tbl_expense_detail__expense_id;
DROP INDEX IF EXISTS landscape.idx_tbl_global_benchmark_registry__source_document_id;
DROP INDEX IF EXISTS landscape.idx_tbl_global_benchmark_registry__source_project_id;
DROP INDEX IF EXISTS landscape.idx_tbl_inventory_item__type_id;
DROP INDEX IF EXISTS landscape.idx_tbl_milestone__phase_id;
DROP INDEX IF EXISTS landscape.idx_tbl_milestone__predecessor_milestone_id;
DROP INDEX IF EXISTS landscape.idx_tbl_milestone__source_doc_id;
DROP INDEX IF EXISTS landscape.idx_tbl_multifamily_unit_type__container_id;
DROP INDEX IF EXISTS landscape.idx_tbl_operations_user_inputs__category_id;
DROP INDEX IF EXISTS landscape.idx_tbl_parcel__area_id;
DROP INDEX IF EXISTS landscape.idx_tbl_parcel__density_code;
DROP INDEX IF EXISTS landscape.idx_tbl_parcel__landuse_code;
DROP INDEX IF EXISTS landscape.idx_tbl_parcel__lot_type_id;
DROP INDEX IF EXISTS landscape.idx_tbl_parcel__phase_id;
DROP INDEX IF EXISTS landscape.idx_tbl_phase__area_id;
DROP INDEX IF EXISTS landscape.idx_tbl_project__dms_template_id;
DROP INDEX IF EXISTS landscape.idx_tbl_project_assumption__source_doc_id;
DROP INDEX IF EXISTS landscape.idx_tbl_rent_roll_unit__project_id;
DROP INDEX IF EXISTS landscape.idx_tbl_scenario__cloned_from_scenario_id;
DROP INDEX IF EXISTS landscape.idx_tbl_scenario__created_by;
DROP INDEX IF EXISTS landscape.idx_type_lot_product__product_id;
DROP INDEX IF EXISTS landscape.idx_assumption_history_user;
DROP INDEX IF EXISTS landscape.idx_assumption_history_org;
DROP INDEX IF EXISTS landscape.idx_assumption_history_project;
DROP INDEX IF EXISTS landscape.idx_assumption_history_property_type;
DROP INDEX IF EXISTS landscape.idx_assumption_history_category_key;
DROP INDEX IF EXISTS landscape.idx_assumption_history_market;
DROP INDEX IF EXISTS landscape.idx_assumption_history_embedding;
DROP INDEX IF EXISTS landscape.idx_user_doc_chunks_doc;
DROP INDEX IF EXISTS landscape.idx_user_doc_chunks_project;
DROP INDEX IF EXISTS landscape.idx_user_doc_chunks_org;
DROP INDEX IF EXISTS landscape.idx_user_doc_chunks_user;
DROP INDEX IF EXISTS landscape.idx_user_doc_chunks_type;
DROP INDEX IF EXISTS landscape.idx_user_doc_chunks_property_type;
DROP INDEX IF EXISTS landscape.idx_user_doc_chunks_embedding;
DROP INDEX IF EXISTS landscape.idx_user_doc_chunks_entities;
DROP INDEX IF EXISTS landscape.idx_user_comparables_user;
DROP INDEX IF EXISTS landscape.idx_user_comparables_org;
DROP INDEX IF EXISTS landscape.idx_user_comparables_project;
DROP INDEX IF EXISTS landscape.idx_user_comparables_type;
DROP INDEX IF EXISTS landscape.idx_user_comparables_property_type;
DROP INDEX IF EXISTS landscape.idx_user_comparables_market;
DROP INDEX IF EXISTS landscape.idx_user_comparables_date;
DROP INDEX IF EXISTS landscape.idx_user_comparables_embedding;
DROP INDEX IF EXISTS landscape.idx_user_comparables_metrics;
DROP INDEX IF EXISTS landscape.idx_source_authority_project;
DROP INDEX IF EXISTS landscape.idx_source_authority_docs;
DROP INDEX IF EXISTS landscape.uq_mkt_recorded_sales_natural;
DROP INDEX IF EXISTS landscape.idx_mkt_recorded_sales_latlng;
DROP INDEX IF EXISTS landscape.idx_mkt_recorded_sales_sale_date;
DROP INDEX IF EXISTS landscape.idx_mkt_recorded_sales_year_built;
DROP INDEX IF EXISTS landscape.idx_mkt_recorded_sales_arms_length;
DROP INDEX IF EXISTS landscape.idx_pk_chapters_topics;
DROP INDEX IF EXISTS landscape.idx_pk_chapters_property_types;
DROP INDEX IF EXISTS landscape.idx_analysis_type_config_type;
DROP INDEX IF EXISTS landscape.idx_narrative_version_project_approach;
DROP INDEX IF EXISTS landscape.idx_narrative_version_status;
DROP INDEX IF EXISTS landscape.idx_narrative_comment_version;
DROP INDEX IF EXISTS landscape.idx_narrative_comment_unresolved;
DROP INDEX IF EXISTS landscape.idx_narrative_change_version;
DROP INDEX IF EXISTS landscape.idx_narrative_change_pending;
DROP INDEX IF EXISTS landscape.idx_research_pub_type;
DROP INDEX IF EXISTS landscape.idx_research_pub_date;
DROP INDEX IF EXISTS landscape.idx_research_pub_categories;
DROP INDEX IF EXISTS landscape.idx_research_pub_tags;
DROP INDEX IF EXISTS landscape.idx_research_fin_proptype;
DROP INDEX IF EXISTS landscape.idx_research_fin_geo;
DROP INDEX IF EXISTS landscape.idx_research_fin_date;
DROP INDEX IF EXISTS landscape.idx_harvest_log_source;
DROP TABLE IF EXISTS landscape.tbl_assumption_history CASCADE;
DROP TABLE IF EXISTS landscape.tbl_user_document_chunks CASCADE;
DROP TABLE IF EXISTS landscape.tbl_user_comparables CASCADE;
DROP TABLE IF EXISTS landscape.ingestion_source_authority CASCADE;
DROP TABLE IF EXISTS landscape.mkt_recorded_sales CASCADE;

-- end
