# Generated by Django 5.0.1 on 2025-11-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE landscape.tbl_acquisition
                ADD COLUMN IF NOT EXISTS goes_hard_date DATE NULL;

                ALTER TABLE landscape.tbl_acquisition
                ADD COLUMN IF NOT EXISTS is_conditional BOOLEAN NULL DEFAULT FALSE;
            """,
            reverse_sql="""
                ALTER TABLE landscape.tbl_acquisition
                DROP COLUMN IF EXISTS goes_hard_date;

                ALTER TABLE landscape.tbl_acquisition
                DROP COLUMN IF EXISTS is_conditional;
            """
        ),
    ]
