# Generated by Django 4.2.25 on 2025-11-30 20:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acquisition', '0001_add_goes_hard_and_conditional_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionEvent',
            fields=[
                ('acquisition_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_id', models.IntegerField(blank=True, help_text='Reference to contact (buyer, seller, etc.)', null=True)),
                ('event_date', models.DateField(blank=True, help_text='Date of the acquisition event', null=True)),
                ('event_type', models.CharField(blank=True, help_text='Type of event: Deposit, Credit, Fee, etc.', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Event description', null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Transaction amount', max_digits=15, null=True)),
                ('is_applied_to_purchase', models.BooleanField(default=True, help_text='Whether this event affects the net purchase price')),
                ('goes_hard_date', models.DateField(blank=True, help_text='Date when deposit becomes non-refundable (goes hard)', null=True)),
                ('is_conditional', models.BooleanField(blank=True, help_text='Whether this event is conditional', null=True)),
                ('units_conveyed', models.DecimalField(blank=True, decimal_places=2, help_text='Units conveyed (acres, SF, etc.)', max_digits=10, null=True)),
                ('measure_id', models.IntegerField(blank=True, help_text='Reference to unit of measure', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_acquisition',
                'ordering': ['event_date', 'acquisition_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyAcquisition',
            fields=[
                ('acquisition_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Purchase price', max_digits=15)),
                ('acquisition_date', models.DateField(help_text='Acquisition date')),
                ('hold_period_years', models.DecimalField(decimal_places=2, help_text='Expected hold period in years', max_digits=5)),
                ('exit_cap_rate', models.DecimalField(decimal_places=4, help_text='Exit cap rate for disposition', max_digits=6)),
                ('sale_date', models.DateField(blank=True, help_text='Planned or actual sale date', null=True)),
                ('closing_costs_pct', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.015'), help_text='Closing costs as % of purchase price', max_digits=6, null=True)),
                ('due_diligence_days', models.IntegerField(blank=True, default=30, help_text='Due diligence period in days', null=True)),
                ('earnest_money', models.DecimalField(blank=True, decimal_places=2, help_text='Earnest money deposit amount', max_digits=12, null=True)),
                ('sale_costs_pct', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.015'), help_text='Sale closing costs as % of sale price', max_digits=6, null=True)),
                ('broker_commission_pct', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.025'), help_text='Broker commission as % of sale price', max_digits=6, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit (per door, per lot, etc.)', max_digits=10, null=True)),
                ('price_per_sf', models.DecimalField(blank=True, decimal_places=2, help_text='Price per square foot', max_digits=8, null=True)),
                ('legal_fees', models.DecimalField(blank=True, decimal_places=2, help_text='Legal fees', max_digits=10, null=True)),
                ('financing_fees', models.DecimalField(blank=True, decimal_places=2, help_text='Financing/loan fees', max_digits=10, null=True)),
                ('third_party_reports', models.DecimalField(blank=True, decimal_places=2, help_text='Third-party reports (appraisals, inspections, etc.)', max_digits=10, null=True)),
                ('depreciation_basis', models.DecimalField(blank=True, decimal_places=2, help_text='Depreciable basis for tax purposes', max_digits=15, null=True)),
                ('land_pct', models.DecimalField(blank=True, decimal_places=2, default=Decimal('20.0'), help_text='Land percentage of total basis', max_digits=5, null=True)),
                ('improvement_pct', models.DecimalField(blank=True, decimal_places=2, default=Decimal('80.0'), help_text='Improvement percentage of total basis', max_digits=5, null=True)),
                ('is_1031_exchange', models.BooleanField(default=False, help_text='Whether this is part of a 1031 exchange')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_property_acquisition',
                'ordering': ['-acquisition_date'],
                'managed': False,
            },
        ),
    ]
