# Generated by Django 5.0.1 on 2026-01-25 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TesterFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(help_text='Full URL including query params', max_length=500)),
                ('page_path', models.CharField(help_text='Path portion of URL, e.g., /projects/123/valuation', max_length=255)),
                ('project_id', models.IntegerField(blank=True, help_text='Project ID if on a project page', null=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback_type', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('question', 'Question'), ('general', 'General Feedback')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_feedback', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tester Feedback',
                'verbose_name_plural': 'Tester Feedback',
                'db_table': 'landscape"."tester_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
