#!/usr/bin/env bash
#
# scripts/nightly/commit-generated-docs.sh — FB-304
#
# Scoped committer for the nightly Landscape sync. Stages and commits ONLY
# generated documentation artifacts. It is structurally impossible for this
# script to commit working-tree code:
#
#   1. It only ever considers paths matched by an explicit ALLOWLIST of glob
#      patterns (generated outputs).
#   2. A guard aborts if any resolved path matches a source-code pattern
#      (defense in depth — should never trigger given the allowlist).
#   3. The final `git commit` is given those exact pathspecs, so even if other
#      files are staged in the index, the commit captures nothing but the
#      listed generated docs.
#
# This replaces the prior `git add -A` / `git add docs/ CLAUDE.md` step in the
# untracked `nightly-landscape-sync` Cowork skill. On 2026-05-19 that step swept
# in-flight backend code (ai_handler.py, tool_schemas.py, services.py,
# registered_report_guard.py, artifact_adapter.py) into a commit mislabeled
# "docs: nightly health check ...", requiring a safety-branch + hard-reset +
# cherry-pick recovery. Moving the logic here makes it version-controlled and
# reviewable, and removes the LLM's discretion to run raw `git add`.
#
# Usage:
#   scripts/nightly/commit-generated-docs.sh             # stage + commit scoped docs
#   scripts/nightly/commit-generated-docs.sh --dry-run   # show what WOULD commit; commit nothing
#
# Exit codes: 0 = committed or nothing to do; 1 = guard abort (code detected).

set -euo pipefail
shopt -s nullglob

DRY_RUN=false
if [ "${1:-}" = "--dry-run" ]; then
  DRY_RUN=true
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

# ── Allowlist: purely-generated artifacts the nightly job legitimately produces.
#    Globs are expanded against the working tree (nullglob → empty if no match).
#    Add new generated outputs here — never broaden to a directory or `-A`.
ALLOWLIST_GLOBS=(
  docs/09_session_notes/*-daily-sync.md   # generated daily-sync notes
  docs/UX/health-reports/*.json           # generated by scripts/health/run-health-check.sh
)

# ── Deny pattern: anything matching is code/source and must never be committed
#    by this job. Belt-and-suspenders on top of the allowlist + scoped commit.
DENY_REGEX='(^|/)(src|backend|services|scripts|migrations)/|\.(ts|tsx|js|jsx|mjs|cjs|py|sql|css|scss|sh)$'

# Expand allowlist globs into concrete candidate paths.
candidates=()
for glob in "${ALLOWLIST_GLOBS[@]}"; do
  for path in $glob; do
    candidates+=("$path")
  done
done

# Keep only paths git reports as changed (modified, staged, or untracked).
changed=()
for path in "${candidates[@]}"; do
  if [ -n "$(git status --porcelain -- "$path" 2>/dev/null)" ]; then
    changed+=("$path")
  fi
done

if [ "${#changed[@]}" -eq 0 ]; then
  echo "FB-304 committer: no generated-doc changes to commit." >&2
  exit 0
fi

# ── Guard: every change must be allowlisted AND must not look like source code.
for path in "${changed[@]}"; do
  if printf '%s' "$path" | grep -qE "$DENY_REGEX"; then
    echo "FB-304 GUARD ABORT: '$path' matched a code/source pattern — refusing to commit." >&2
    echo "  This should be impossible given the allowlist; investigate ALLOWLIST_GLOBS." >&2
    exit 1
  fi
done

echo "FB-304 committer: generated docs eligible for commit:" >&2
printf '   + %s\n' "${changed[@]}" >&2

if [ "$DRY_RUN" = true ]; then
  # Prove the staged set without committing or disturbing the working tree:
  # stage the allowlist, print the cached name list, then unstage (files on
  # disk are untouched; any pre-existing staged paths for OTHER files are left
  # exactly as they were).
  git add -- "${changed[@]}"
  echo "--- DRY RUN: git diff --cached --name-only ---" >&2
  git diff --cached --name-only -- "${changed[@]}"
  git restore --staged -- "${changed[@]}"
  echo "FB-304 committer: dry-run complete; nothing committed." >&2
  exit 0
fi

# Commit ONLY the allowlisted pathspecs. Other staged/unstaged changes (e.g.
# in-flight code) are not part of this commit.
git add -- "${changed[@]}"
git commit -m "docs: nightly health check $(date +%Y-%m-%d)" -- "${changed[@]}"
echo "FB-304 committer: committed ${#changed[@]} generated-doc file(s)." >&2
