# Generated by Django 5.0.1 on 2025-12-09 15:48

import django.db.models.deletion
from django.db import migrations, models


def seed_data_sources(apps, schema_editor):
    """Seed initial data sources for market intelligence."""
    MktDataSourceRegistry = apps.get_model('market_intel', 'MktDataSourceRegistry')

    sources = [
        {
            'source_code': 'ZONDA',
            'source_name': 'Zonda Research (formerly Metrostudy)',
            'source_type': 'subdivision_survey',
            'collection_method': 'Quarterly field surveys by trained researchers who physically visit communities, count inventory stages, and collect pricing from sales offices',
            'update_frequency': 'Quarterly',
            'typical_lag_days': 30,
            'coverage_geography': 'Phoenix-Mesa-Chandler MSA',
            'coverage_description': 'New construction subdivisions only; excludes custom homes, infill, and build-on-your-lot',
            'field_definitions': {
                'sales_rate': 'Monthly velocity calculated from total units sold divided by months since open date',
                'units_sold': 'Cumulative sales from subdivision open date',
                'qmi': 'Quick Move-In inventory (spec homes)',
                'vdl': 'Vacant Developed Lots ready for construction'
            },
            'known_limitations': 'Active Adult communities tracked separately; lot widths often missing for older subdivisions',
            'caveats': 'Sales rates may differ from permit counts due to timing differences between contract and permit',
            'is_authoritative_for': ['subdivision_pricing', 'builder_inventory', 'product_mix', 'absorption_rates'],
            'website_url': 'https://zonda.com',
            'is_active': True,
        },
        {
            'source_code': 'HBACA',
            'source_name': 'Home Builders Association of Central Arizona',
            'source_type': 'permit_data',
            'collection_method': 'Monthly compilation of single-family building permits from municipal building departments',
            'update_frequency': 'Monthly',
            'typical_lag_days': 15,
            'coverage_geography': 'Phoenix MSA (22 jurisdictions)',
            'coverage_description': 'Single-family permits only; source of truth for permit volume by jurisdiction',
            'field_definitions': {
                'permits_sf': 'Single-family residential building permits issued by jurisdiction'
            },
            'known_limitations': 'Does not include multi-family permits; some jurisdictions report with delay',
            'caveats': 'Permit counts may differ from Zonda sales due to timing (permits precede sales)',
            'is_authoritative_for': ['permit_counts', 'jurisdiction_totals'],
            'website_url': 'https://hbaca.org',
            'is_active': True,
        },
        {
            'source_code': 'MANUAL',
            'source_name': 'Manual Entry',
            'source_type': 'user_input',
            'collection_method': 'User-entered data from various sources',
            'update_frequency': 'Ad-hoc',
            'typical_lag_days': 0,
            'coverage_geography': 'Varies',
            'coverage_description': 'User-supplied market data; verify source documentation',
            'field_definitions': {},
            'is_authoritative_for': [],
            'is_active': True,
        },
    ]

    for source_data in sources:
        MktDataSourceRegistry.objects.update_or_create(
            source_code=source_data['source_code'],
            defaults=source_data
        )


def create_landscaper_views(apps, schema_editor):
    """Create views for Landscaper AI queries."""
    from django.db import connection

    views_sql = """
    -- View: Current Active Projects (Most Recent Snapshot)
    CREATE OR REPLACE VIEW landscape.vw_mkt_current_projects AS
    WITH latest AS (
        SELECT source_project_id, source_id, MAX(effective_date) as latest_date
        FROM landscape.mkt_new_home_project
        WHERE source_project_id IS NOT NULL
        GROUP BY source_project_id, source_id
    )
    SELECT p.*
    FROM landscape.mkt_new_home_project p
    JOIN latest l ON p.source_project_id = l.source_project_id
        AND p.source_id = l.source_id
        AND p.effective_date = l.latest_date
    WHERE p.status = 'Active';

    -- View: Absorption Benchmarks by Lot Width
    CREATE OR REPLACE VIEW landscape.vw_mkt_absorption_by_lot_width AS
    SELECT
        lot_width_ft,
        effective_date,
        COUNT(*) as project_count,
        ROUND(AVG(sales_rate_monthly)::numeric, 2) as avg_monthly_rate,
        ROUND(AVG(sales_rate_3m_avg)::numeric, 2) as avg_3m_rate,
        ROUND(PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY sales_rate_monthly)::numeric, 2) as rate_p25,
        ROUND(PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY sales_rate_monthly)::numeric, 2) as rate_median,
        ROUND(PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY sales_rate_monthly)::numeric, 2) as rate_p75,
        ROUND(AVG(price_avg)::numeric, 0) as avg_price,
        ROUND(AVG(mos_vdl)::numeric, 1) as avg_mos_vdl
    FROM landscape.mkt_new_home_project
    WHERE lot_width_ft IS NOT NULL
        AND sales_rate_monthly IS NOT NULL
        AND status = 'Active'
    GROUP BY lot_width_ft, effective_date
    ORDER BY lot_width_ft, effective_date;

    -- View: Absorption Benchmarks by Land Use Product Code
    CREATE OR REPLACE VIEW landscape.vw_mkt_absorption_by_lu_product AS
    SELECT
        p.lu_product_id,
        lp.code as product_code,
        p.effective_date,
        COUNT(*) as project_count,
        ROUND(AVG(p.sales_rate_monthly)::numeric, 2) as avg_monthly_rate,
        ROUND(AVG(p.sales_rate_3m_avg)::numeric, 2) as avg_3m_rate,
        ROUND(AVG(p.price_avg)::numeric, 0) as avg_price
    FROM landscape.mkt_new_home_project p
    LEFT JOIN landscape.res_lot_product lp ON p.lu_product_id = lp.product_id
    WHERE p.lu_product_id IS NOT NULL
        AND p.sales_rate_monthly IS NOT NULL
        AND p.status = 'Active'
    GROUP BY p.lu_product_id, lp.code, p.effective_date
    ORDER BY lp.code, p.effective_date;

    -- View: Market Pricing by City and Lot Width
    CREATE OR REPLACE VIEW landscape.vw_mkt_pricing_by_city_lotwidth AS
    SELECT
        city,
        lot_width_ft,
        effective_date,
        COUNT(*) as project_count,
        ROUND(AVG(price_avg)::numeric, 0) as avg_price,
        ROUND(MIN(price_min)::numeric, 0) as min_price,
        ROUND(MAX(price_max)::numeric, 0) as max_price,
        ROUND(AVG(price_per_sf_avg)::numeric, 2) as avg_price_psf
    FROM landscape.mkt_new_home_project
    WHERE city IS NOT NULL
        AND lot_width_ft IS NOT NULL
        AND price_avg IS NOT NULL
        AND status = 'Active'
    GROUP BY city, lot_width_ft, effective_date
    ORDER BY city, lot_width_ft, effective_date;

    -- View: Annual Permit Totals by Jurisdiction
    CREATE OR REPLACE VIEW landscape.vw_permit_annual_by_jurisdiction AS
    SELECT
        jurisdiction_name,
        EXTRACT(YEAR FROM permit_month)::integer as permit_year,
        SUM(permits_sf) as annual_permits_sf,
        SUM(COALESCE(permits_total, permits_sf)) as annual_permits_total,
        source_id
    FROM landscape.mkt_permit_history
    GROUP BY jurisdiction_name, EXTRACT(YEAR FROM permit_month), source_id
    ORDER BY jurisdiction_name, permit_year;

    -- View: MSA Totals by Month
    CREATE OR REPLACE VIEW landscape.vw_permit_msa_monthly AS
    SELECT
        permit_month,
        EXTRACT(YEAR FROM permit_month)::integer as permit_year,
        SUM(permits_sf) as msa_permits_sf,
        SUM(COALESCE(permits_total, permits_sf)) as msa_permits_total,
        COUNT(DISTINCT jurisdiction_name) as jurisdiction_count,
        source_id
    FROM landscape.mkt_permit_history
    GROUP BY permit_month, EXTRACT(YEAR FROM permit_month), source_id
    ORDER BY permit_month;

    -- View: Market Summary for Landscaper AI
    CREATE OR REPLACE VIEW landscape.vw_mkt_landscaper_summary AS
    WITH current_projects AS (
        SELECT * FROM landscape.vw_mkt_current_projects
    )
    SELECT
        city,
        lot_width_ft,
        COUNT(*) as active_communities,
        SUM(units_remaining) as total_units_available,
        ROUND(AVG(sales_rate_monthly)::numeric, 2) as avg_absorption_rate,
        ROUND(AVG(price_avg)::numeric, 0) as avg_price,
        ROUND(MIN(price_min)::numeric, 0) as market_entry_price,
        ROUND(MAX(price_max)::numeric, 0) as market_ceiling_price
    FROM current_projects
    WHERE city IS NOT NULL AND lot_width_ft IS NOT NULL
    GROUP BY city, lot_width_ft
    ORDER BY city, lot_width_ft;
    """

    with connection.cursor() as cursor:
        # Execute each statement separately
        for statement in views_sql.split(';'):
            statement = statement.strip()
            if statement and not statement.startswith('--'):
                cursor.execute(statement)


def drop_landscaper_views(apps, schema_editor):
    """Drop Landscaper AI views on reverse migration."""
    from django.db import connection

    views = [
        'vw_mkt_current_projects',
        'vw_mkt_absorption_by_lot_width',
        'vw_mkt_absorption_by_lu_product',
        'vw_mkt_pricing_by_city_lotwidth',
        'vw_permit_annual_by_jurisdiction',
        'vw_permit_msa_monthly',
        'vw_mkt_landscaper_summary',
    ]

    with connection.cursor() as cursor:
        for view in views:
            cursor.execute(f"DROP VIEW IF EXISTS landscape.{view} CASCADE")


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIIngestionHistory",
            fields=[
                ("ingestion_id", models.AutoField(primary_key=True, serialize=False)),
                ("doc_id", models.BigIntegerField()),
                ("ingestion_date", models.DateTimeField(auto_now_add=True)),
                ("model_used", models.CharField(max_length=100)),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("extracted_data", models.JSONField(default=dict)),
                ("validation_status", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ai_ingestion_history",
                "ordering": ["-ingestion_date"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MarketCompetitiveProject",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("comp_name", models.CharField(max_length=200)),
                ("comp_address", models.TextField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("total_units", models.IntegerField(blank=True, null=True)),
                (
                    "price_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "price_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "absorption_rate_monthly",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Units per month",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="selling",
                        help_text="selling, sold_out, planned",
                        max_length=50,
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        default="manual",
                        help_text="manual, landscaper_ai, mls, public_records",
                        max_length=50,
                    ),
                ),
                ("source_url", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "market_competitive_projects",
                "ordering": ["project", "-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MarketMacroData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "population_growth_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "employment_trend",
                    models.CharField(
                        blank=True,
                        help_text="growing, stable, declining",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "household_formation_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("building_permits_annual", models.IntegerField(blank=True, null=True)),
                (
                    "median_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("data_year", models.IntegerField(blank=True, null=True)),
                (
                    "data_source",
                    models.CharField(
                        default="manual",
                        help_text="manual, landscaper_ai, census, bls",
                        max_length=50,
                    ),
                ),
                ("source_url", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "market_macro_data",
                "ordering": ["project", "-data_year"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MarketRateAnalysis",
            fields=[
                ("analysis_id", models.AutoField(primary_key=True, serialize=False)),
                ("unit_type", models.CharField(max_length=50)),
                ("bedrooms", models.DecimalField(decimal_places=1, max_digits=3)),
                ("bathrooms", models.DecimalField(decimal_places=1, max_digits=3)),
                ("subject_sqft", models.IntegerField()),
                ("comp_count", models.IntegerField()),
                (
                    "min_rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "avg_rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "median_rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "avg_rent_per_sf",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "location_adjustment",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Percentage adjustment",
                        max_digits=6,
                    ),
                ),
                (
                    "condition_adjustment",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Percentage adjustment",
                        max_digits=6,
                    ),
                ),
                (
                    "amenity_adjustment",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Percentage adjustment",
                        max_digits=6,
                    ),
                ),
                (
                    "size_adjustment_per_sf",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="$/SF adjustment",
                        max_digits=6,
                    ),
                ),
                (
                    "recommended_market_rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "recommended_rent_per_sf",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("confidence_level", models.CharField(default="MEDIUM", max_length=20)),
                ("analysis_notes", models.TextField(blank=True, null=True)),
                (
                    "analyzed_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("analysis_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tbl_market_rate_analysis",
                "ordering": ["project", "bedrooms", "bathrooms"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RentComparable",
            fields=[
                ("comparable_id", models.AutoField(primary_key=True, serialize=False)),
                ("property_name", models.CharField(max_length=200)),
                ("address", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "distance_miles",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("year_built", models.IntegerField(blank=True, null=True)),
                ("total_units", models.IntegerField(blank=True, null=True)),
                ("unit_type", models.CharField(max_length=50)),
                ("bedrooms", models.DecimalField(decimal_places=1, max_digits=3)),
                ("bathrooms", models.DecimalField(decimal_places=1, max_digits=3)),
                ("avg_sqft", models.IntegerField()),
                ("asking_rent", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "effective_rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "concessions",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("amenities", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "data_source",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("as_of_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tbl_rent_comparable",
                "ordering": ["project", "distance_miles", "unit_type"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MktDataSourceRegistry",
            fields=[
                ("source_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "source_code",
                    models.CharField(
                        help_text="ZONDA, HBACA, ATTOM, ARMLS, CENSUS_PERMITS",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        help_text="Zonda Research, Home Builders Association of Central Arizona",
                        max_length=200,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("subdivision_survey", "Subdivision Survey"),
                            ("permit_data", "Permit Data"),
                            ("mls_feed", "MLS Feed"),
                            ("property_data", "Property Data"),
                            ("user_input", "User Input"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "collection_method",
                    models.TextField(
                        blank=True, help_text="How data is collected", null=True
                    ),
                ),
                (
                    "update_frequency",
                    models.CharField(
                        blank=True,
                        help_text="Quarterly, Monthly, Daily, Annual",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "typical_lag_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Days between observation and data availability",
                        null=True,
                    ),
                ),
                (
                    "coverage_geography",
                    models.CharField(
                        blank=True,
                        help_text="Phoenix-Mesa-Chandler MSA, National",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "coverage_description",
                    models.TextField(
                        blank=True, help_text="What is/isn't included", null=True
                    ),
                ),
                (
                    "field_definitions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"sales_rate": "Monthly velocity from field counts"}',
                    ),
                ),
                ("known_limitations", models.TextField(blank=True, null=True)),
                ("caveats", models.TextField(blank=True, null=True)),
                (
                    "is_authoritative_for",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='["permit_counts", "jurisdiction_totals"]',
                    ),
                ),
                ("website_url", models.TextField(blank=True, null=True)),
                ("documentation_url", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Market Data Source",
                "verbose_name_plural": "Market Data Sources",
                "db_table": "mkt_data_source_registry",
                "ordering": ["source_code"],
            },
        ),
        migrations.CreateModel(
            name="MktPermitHistory",
            fields=[
                ("record_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "source_file",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "permit_month",
                    models.DateField(help_text="First day of month: 2025-01-01"),
                ),
                (
                    "jurisdiction_name",
                    models.CharField(
                        help_text="Surprise, Buckeye, Phoenix", max_length=100
                    ),
                ),
                (
                    "jurisdiction_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("City", "City"),
                            ("Town", "Town"),
                            ("County", "County"),
                            ("CDP", "Census Designated Place"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("county", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(default="AZ", max_length=2)),
                ("cbsa_code", models.IntegerField(blank=True, null=True)),
                (
                    "permits_sf",
                    models.IntegerField(
                        blank=True, help_text="Single-family", null=True
                    ),
                ),
                (
                    "permits_mf",
                    models.IntegerField(
                        blank=True, help_text="Multi-family", null=True
                    ),
                ),
                (
                    "permits_total",
                    models.IntegerField(
                        blank=True,
                        help_text="Total (may be SF only for HBACA)",
                        null=True,
                    ),
                ),
                ("permits_detached", models.IntegerField(blank=True, null=True)),
                ("permits_attached", models.IntegerField(blank=True, null=True)),
                ("permits_custom", models.IntegerField(blank=True, null=True)),
                ("ingestion_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        db_column="source_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="permit_records",
                        to="market_intel.mktdatasourceregistry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permit History",
                "verbose_name_plural": "Permit History",
                "db_table": "mkt_permit_history",
                "ordering": ["-permit_month", "jurisdiction_name"],
            },
        ),
        migrations.CreateModel(
            name="MktNewHomeProject",
            fields=[
                ("record_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "source_project_id",
                    models.CharField(
                        blank=True,
                        help_text="Original ID from source (Zonda Universal ID)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "source_subdivision_id",
                    models.CharField(
                        blank=True,
                        help_text="Parent subdivision ID if applicable",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(help_text="Date this snapshot represents"),
                ),
                (
                    "source_file",
                    models.CharField(
                        blank=True,
                        help_text="Filename of import",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "survey_period",
                    models.CharField(
                        blank=True,
                        help_text="Source's period label: 2025Q3, 2025-12",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("project_name", models.CharField(max_length=200)),
                (
                    "master_plan_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "master_plan_id",
                    models.CharField(
                        blank=True,
                        help_text="Source's MPC identifier",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "master_plan_developer",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "builder_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "parent_builder",
                    models.CharField(
                        blank=True,
                        help_text="Corporate parent: PulteGroup Inc.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Active", "Active"),
                            ("Sold Out", "Sold Out"),
                            ("Future", "Future"),
                            ("On Hold", "On Hold"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Detached", "Detached"),
                            ("Attached", "Attached"),
                            ("Condo", "Condo"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "product_style",
                    models.CharField(
                        blank=True,
                        help_text="Single-Family, Townhome, Duet",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("is_active_adult", models.BooleanField(default=False)),
                (
                    "characteristics",
                    models.TextField(
                        blank=True, help_text="Active Adult; Gated; Golf", null=True
                    ),
                ),
                ("lot_size_sf", models.IntegerField(blank=True, null=True)),
                ("lot_width_ft", models.IntegerField(blank=True, null=True)),
                ("lot_depth_ft", models.IntegerField(blank=True, null=True)),
                (
                    "lot_dimensions",
                    models.CharField(
                        blank=True, help_text="50x115 format", max_length=20, null=True
                    ),
                ),
                ("unit_size_min_sf", models.IntegerField(blank=True, null=True)),
                ("unit_size_max_sf", models.IntegerField(blank=True, null=True)),
                ("unit_size_avg_sf", models.IntegerField(blank=True, null=True)),
                (
                    "price_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "price_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "price_avg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "price_per_sf_avg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("price_change_date", models.DateField(blank=True, null=True)),
                ("units_planned", models.IntegerField(blank=True, null=True)),
                ("units_sold", models.IntegerField(blank=True, null=True)),
                ("units_remaining", models.IntegerField(blank=True, null=True)),
                (
                    "qmi_count",
                    models.IntegerField(
                        blank=True, help_text="Quick Move-In / spec homes", null=True
                    ),
                ),
                ("open_date", models.DateField(blank=True, null=True)),
                ("sold_out_date", models.DateField(blank=True, null=True)),
                (
                    "sales_rate_monthly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "sales_rate_3m_avg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "sales_rate_6m_avg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "sales_rate_12m_avg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("sales_change_date", models.DateField(blank=True, null=True)),
                ("annual_starts", models.IntegerField(blank=True, null=True)),
                ("annual_closings", models.IntegerField(blank=True, null=True)),
                ("quarterly_starts", models.IntegerField(blank=True, null=True)),
                ("quarterly_closings", models.IntegerField(blank=True, null=True)),
                ("pipeline_excavation", models.IntegerField(blank=True, null=True)),
                ("pipeline_survey_stakes", models.IntegerField(blank=True, null=True)),
                ("pipeline_street_paving", models.IntegerField(blank=True, null=True)),
                ("pipeline_streets_in", models.IntegerField(blank=True, null=True)),
                (
                    "pipeline_vdl",
                    models.IntegerField(
                        blank=True, help_text="Vacant Developed Lots", null=True
                    ),
                ),
                ("pipeline_vacant_land", models.IntegerField(blank=True, null=True)),
                (
                    "pipeline_under_construction",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "pipeline_finished_vacant",
                    models.IntegerField(blank=True, null=True),
                ),
                ("models_count", models.IntegerField(blank=True, null=True)),
                ("occupied_count", models.IntegerField(blank=True, null=True)),
                ("future_inventory_count", models.IntegerField(blank=True, null=True)),
                (
                    "mos_vdl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Months of Supply at VDL stage",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "mos_inventory",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "mos_finished_vacant",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "incentive_qmi_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "incentive_qmi_amt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "incentive_qmi_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "incentive_tbb_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="To Be Built",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "incentive_tbb_amt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "incentive_tbb_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "incentive_broker_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "incentive_broker_amt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "incentive_broker_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hoa_fee_monthly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "hoa_fee_2_monthly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "hoa_fee_per_sqft",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "assessment_rate",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                ("assessment_description", models.TextField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=11, null=True
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=300, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
                ("county", models.CharField(blank=True, max_length=100, null=True)),
                ("county_fips", models.IntegerField(blank=True, null=True)),
                ("cbsa_name", models.CharField(blank=True, max_length=100, null=True)),
                ("cbsa_code", models.IntegerField(blank=True, null=True)),
                ("state", models.CharField(blank=True, max_length=2, null=True)),
                ("boundary_names", models.TextField(blank=True, null=True)),
                (
                    "school_district",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("school_elementary", models.TextField(blank=True, null=True)),
                (
                    "school_rating_elementary",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("school_middle", models.TextField(blank=True, null=True)),
                (
                    "school_rating_middle",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("school_high", models.TextField(blank=True, null=True)),
                (
                    "school_rating_high",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("website_url", models.TextField(blank=True, null=True)),
                (
                    "office_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "lu_family_id",
                    models.BigIntegerField(
                        blank=True, help_text="FK to lu_family.family_id", null=True
                    ),
                ),
                (
                    "lu_density_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="FK to density_classification.density_id",
                        null=True,
                    ),
                ),
                (
                    "lu_type_id",
                    models.BigIntegerField(
                        blank=True, help_text="FK to lu_type.type_id", null=True
                    ),
                ),
                (
                    "lu_product_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="FK to res_lot_product.product_id",
                        null=True,
                    ),
                ),
                (
                    "lu_linkage_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("auto", "Auto-inferred"),
                            ("user", "User-assigned"),
                            ("ai_suggested", "AI Suggested"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "lu_linkage_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="0.00-1.00 confidence score",
                        max_digits=3,
                        null=True,
                    ),
                ),
                ("ingestion_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        db_column="source_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="new_home_projects",
                        to="market_intel.mktdatasourceregistry",
                    ),
                ),
            ],
            options={
                "verbose_name": "New Home Project Survey",
                "verbose_name_plural": "New Home Project Surveys",
                "db_table": "mkt_new_home_project",
                "ordering": ["-effective_date", "project_name"],
                "indexes": [
                    models.Index(
                        fields=["project_name"], name="idx_mkt_nhp_project_name"
                    ),
                    models.Index(
                        fields=["master_plan_name"], name="idx_mkt_nhp_master_plan"
                    ),
                    models.Index(fields=["builder_name"], name="idx_mkt_nhp_builder"),
                    models.Index(fields=["lot_width_ft"], name="idx_mkt_nhp_lot_width"),
                    models.Index(fields=["city"], name="idx_mkt_nhp_city"),
                    models.Index(
                        fields=["effective_date"], name="idx_mkt_nhp_effective_date"
                    ),
                    models.Index(fields=["source"], name="idx_mkt_nhp_source"),
                    models.Index(fields=["status"], name="idx_mkt_nhp_status"),
                    models.Index(fields=["cbsa_code"], name="idx_mkt_nhp_cbsa"),
                    models.Index(
                        fields=["latitude", "longitude"], name="idx_mkt_nhp_location"
                    ),
                    models.Index(
                        fields=["lu_product_id"], name="idx_mkt_nhp_lu_product"
                    ),
                    models.Index(fields=["lu_type_id"], name="idx_mkt_nhp_lu_type"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="mktnewhomeproject",
            constraint=models.UniqueConstraint(
                fields=("source", "source_project_id", "effective_date"),
                name="uq_mkt_project_source_date",
            ),
        ),
        migrations.AddIndex(
            model_name="mktpermithistory",
            index=models.Index(fields=["permit_month"], name="idx_mkt_permit_month"),
        ),
        migrations.AddIndex(
            model_name="mktpermithistory",
            index=models.Index(
                fields=["jurisdiction_name"], name="idx_mkt_permit_jurisdiction"
            ),
        ),
        migrations.AddIndex(
            model_name="mktpermithistory",
            index=models.Index(fields=["source"], name="idx_mkt_permit_source"),
        ),
        migrations.AddConstraint(
            model_name="mktpermithistory",
            constraint=models.UniqueConstraint(
                fields=("source", "permit_month", "jurisdiction_name"),
                name="uq_mkt_permit_month_jurisdiction",
            ),
        ),
        # Seed data sources
        migrations.RunPython(seed_data_sources, migrations.RunPython.noop),
        # Create Landscaper AI views
        migrations.RunPython(create_landscaper_views, drop_landscaper_views),
    ]
