# Generated by Django 5.0.1 on 2025-12-12 21:15

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEmbedding',
            fields=[
                ('embedding_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('entity', 'Entity'), ('fact', 'Fact'), ('document', 'Document'), ('interaction', 'Interaction')], db_index=True, max_length=50)),
                ('source_id', models.BigIntegerField(db_index=True)),
                ('content_text', models.TextField(help_text='Text content that was embedded')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('entity_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, help_text='Related entity IDs for filtering', size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, help_text='Searchable tags', size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Knowledge Embedding',
                'verbose_name_plural': 'Knowledge Embeddings',
                'db_table': 'landscape"."knowledge_embeddings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='knowledge_e_source__f8627b_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEntity',
            fields=[
                ('entity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('project', 'Project'), ('property', 'Property'), ('unit', 'Unit'), ('unit_type', 'Unit Type'), ('market', 'Market'), ('assumption', 'Assumption'), ('document', 'Document'), ('person', 'Person'), ('company', 'Company'), ('area', 'Area/Container'), ('benchmark', 'Benchmark'), ('other', 'Other')], db_index=True, max_length=50)),
                ('entity_subtype', models.CharField(blank=True, help_text="e.g., 'multifamily', 'office', 'retail', 'mpc'", max_length=100, null=True)),
                ('canonical_name', models.CharField(db_index=True, help_text='Unique identifier for this entity', max_length=500, unique=True)),
                ('metadata', models.JSONField(default=dict, help_text='Type-specific attributes in flexible JSON structure')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Knowledge Entity',
                'verbose_name_plural': 'Knowledge Entities',
                'db_table': 'landscape"."knowledge_entities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeFact',
            fields=[
                ('fact_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('predicate', models.CharField(db_index=True, help_text='Relationship type: has_assumption, located_in, monthly_rent, etc.', max_length=200)),
                ('object_value', models.TextField(blank=True, help_text='Literal value (for non-entity objects)', null=True)),
                ('valid_from', models.DateField(blank=True, help_text='When this fact became true', null=True)),
                ('valid_to', models.DateField(blank=True, help_text='When this fact ceased to be true', null=True)),
                ('source_type', models.CharField(choices=[('user_input', 'User Input'), ('document_extract', 'Document Extraction'), ('market_data', 'Market Data'), ('calculation', 'Calculation'), ('ai_inference', 'AI Inference'), ('user_correction', 'User Correction'), ('import', 'Data Import')], db_index=True, max_length=50)),
                ('source_id', models.BigIntegerField(blank=True, help_text='ID of source record (document_id, calculation_id, etc.)', null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=1.0, help_text='Confidence level 0.00-1.00', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_current', models.BooleanField(db_index=True, default=True, help_text='Whether this is the current version of the fact')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_facts', to=settings.AUTH_USER_MODEL)),
                ('object_entity', models.ForeignKey(blank=True, help_text='Entity reference (for entity-to-entity relationships)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facts_as_object', to='knowledge.knowledgeentity')),
                ('subject_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts_as_subject', to='knowledge.knowledgeentity')),
                ('superseded_by', models.ForeignKey(blank=True, help_text='Newer fact that replaces this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='knowledge.knowledgefact')),
            ],
            options={
                'verbose_name': 'Knowledge Fact',
                'verbose_name_plural': 'Knowledge Facts',
                'db_table': 'landscape"."knowledge_facts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeInsight',
            fields=[
                ('insight_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('anomaly', 'Anomaly Detection'), ('trend', 'Trend Analysis'), ('opportunity', 'Opportunity'), ('risk', 'Risk Alert'), ('benchmark', 'Benchmark Comparison'), ('pattern', 'Pattern Discovery')], db_index=True, max_length=50)),
                ('related_entities', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, help_text='Other entities involved in this insight', size=None)),
                ('insight_title', models.CharField(max_length=500)),
                ('insight_description', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=20)),
                ('supporting_facts', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, help_text='Fact IDs that support this insight', size=None)),
                ('metadata', models.JSONField(default=dict, help_text='Additional insight data (calculations, comparisons, etc.)')),
                ('acknowledged', models.BooleanField(db_index=True, default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('user_action', models.TextField(blank=True, help_text='Action taken by user in response to insight', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_insights', to=settings.AUTH_USER_MODEL)),
                ('subject_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='knowledge.knowledgeentity')),
            ],
            options={
                'verbose_name': 'Knowledge Insight',
                'verbose_name_plural': 'Knowledge Insights',
                'db_table': 'landscape"."knowledge_insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSession',
            fields=[
                ('session_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.IntegerField(blank=True, help_text='Workspace context (if applicable)', null=True)),
                ('project_id', models.IntegerField(blank=True, db_index=True, help_text='Project context (if applicable)', null=True)),
                ('session_start', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('loaded_entities', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, help_text='Array of entity_id values loaded in this session', size=None)),
                ('loaded_facts_count', models.IntegerField(default=0, help_text='Number of facts loaded in context')),
                ('context_token_count', models.IntegerField(default=0, help_text='Estimated token usage for loaded context')),
                ('context_summary', models.TextField(blank=True, help_text='Brief summary of loaded context', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional session metadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Knowledge Session',
                'verbose_name_plural': 'Knowledge Sessions',
                'db_table': 'landscape"."knowledge_sessions',
                'ordering': ['-session_start'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeInteraction',
            fields=[
                ('interaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_query', models.TextField(help_text="User's original query")),
                ('query_type', models.CharField(choices=[('question', 'Question'), ('command', 'Command'), ('clarification', 'Clarification'), ('feedback', 'Feedback')], max_length=50)),
                ('query_intent', models.CharField(blank=True, help_text='Classified intent of query', max_length=200, null=True)),
                ('context_entities', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, help_text='Entity IDs used in context', size=None)),
                ('context_facts', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, help_text='Fact IDs used in context', size=None)),
                ('ai_response', models.TextField(help_text="AI's response")),
                ('response_type', models.CharField(choices=[('answer', 'Direct Answer'), ('clarification_needed', 'Needs Clarification'), ('action_taken', 'Action Taken'), ('error', 'Error')], max_length=50)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('user_feedback', models.CharField(blank=True, choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful'), ('partially_helpful', 'Partially Helpful')], max_length=50, null=True)),
                ('user_correction', models.TextField(blank=True, help_text="User's correction if response was wrong", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='knowledge.knowledgesession')),
            ],
            options={
                'verbose_name': 'Knowledge Interaction',
                'verbose_name_plural': 'Knowledge Interactions',
                'db_table': 'landscape"."knowledge_interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgeentity',
            index=models.Index(fields=['entity_type', 'entity_subtype'], name='knowledge_e_entity__ca2a63_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeentity',
            index=models.Index(fields=['canonical_name'], name='knowledge_e_canonic_a1a8d9_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgefact',
            index=models.Index(fields=['subject_entity', 'predicate'], name='knowledge_f_subject_0aa246_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgefact',
            index=models.Index(fields=['object_entity'], name='knowledge_f_object__4cb694_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgefact',
            index=models.Index(fields=['is_current', 'predicate'], name='knowledge_f_is_curr_84f472_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgefact',
            index=models.Index(fields=['source_type', 'source_id'], name='knowledge_f_source__dd8340_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgefact',
            index=models.Index(fields=['valid_from', 'valid_to'], name='knowledge_f_valid_f_f71d25_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeinsight',
            index=models.Index(fields=['subject_entity', 'insight_type'], name='knowledge_i_subject_c1bcf7_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeinsight',
            index=models.Index(fields=['acknowledged', 'severity'], name='knowledge_i_acknowl_7d6024_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeinsight',
            index=models.Index(fields=['insight_type', 'created_at'], name='knowledge_i_insight_965cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgesession',
            index=models.Index(fields=['user', 'project_id'], name='knowledge_s_user_id_c64165_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgesession',
            index=models.Index(fields=['session_start'], name='knowledge_s_session_5b8f09_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgesession',
            index=models.Index(condition=models.Q(('session_end__isnull', True)), fields=['session_end'], name='idx_active_sessions'),
        ),
        migrations.AddIndex(
            model_name='knowledgeinteraction',
            index=models.Index(fields=['session', 'created_at'], name='knowledge_i_session_7869de_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeinteraction',
            index=models.Index(fields=['query_intent'], name='knowledge_i_query_i_cc952f_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeinteraction',
            index=models.Index(fields=['user_feedback'], name='knowledge_i_user_fe_5c8b7f_idx'),
        ),
    ]
