# Generated by Django 5.0.1 on 2026-01-30 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_add_chunk_metadata'),
        ('knowledge', '0005_create_alpha_feedback_table'),
    ]

    operations = [
    ]
