# Generated by Django 5.0.1 on 2026-02-05 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_merge_20260130_2117'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformknowledge',
            name='knowledge_domain',
            field=models.CharField(choices=[('valuation', 'Valuation'), ('cost', 'Cost'), ('market', 'Market'), ('legal', 'Legal'), ('standards', 'Standards'), ('development', 'Development'), ('operating_expenses', 'Operating Expenses'), ('valuation_methodology', 'Valuation Methodology'), ('market_data', 'Market Data'), ('legal_regulatory', 'Legal/Regulatory'), ('cost_estimation', 'Cost Estimation'), ('alpha_help', 'Alpha Help'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='platformknowledgechunk',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Additional chunk metadata used for filtered retrieval'),
        ),
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_id', models.BigIntegerField(db_index=True)),
                ('document_id', models.BigIntegerField(db_index=True)),
                ('scope', models.CharField(choices=[('rent_roll', 'Rent Roll'), ('operating_statement', 'Operating Statement'), ('proforma', 'Pro Forma'), ('offering_memo', 'Offering Memorandum'), ('other', 'Other')], db_index=True, help_text='Extraction scope: rent_roll, operating_statement, etc.', max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('total_items', models.IntegerField(blank=True, null=True)),
                ('processed_items', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('result_summary', models.JSONField(blank=True, help_text='Summary: {fills: N, conflicts: N, total: N}', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extraction Job',
                'verbose_name_plural': 'Extraction Jobs',
                'db_table': 'landscape"."tbl_extraction_job',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project_id', 'scope', 'status'], name='tbl_extract_project_e44a1d_idx'), models.Index(fields=['project_id', 'created_at'], name='tbl_extract_project_f3cb1f_idx')],
            },
        ),
    ]
