version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces/${localWorkspaceFolderBasename}:cached
    command: sleep infinity
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    working_dir: /workspaces/${localWorkspaceFolderBasename}