-- Migration: 2025-10-23_subdivision_underwriting_v1
-- Purpose : Add tables for parcel underwriting (A,C,E,F,G) and extend tbl_budget (B)
-- Schema  : landscape
-- Notes   : Idempotent; safe to re-run; emits NOTICES when skipping existing artifacts
BEGIN;
SET search_path TO landscape, public;

-- ============================================================================
-- Section B: Extend landscape.tbl_budget with underwriting flags and rate hook
-- ============================================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'landscape' AND table_name = 'tbl_budget' AND column_name = 'rate_profile_id'
  ) THEN
    ALTER TABLE landscape.tbl_budget ADD COLUMN rate_profile_id VARCHAR(64);
    RAISE NOTICE 'Added column landscape.tbl_budget.rate_profile_id';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'landscape' AND table_name = 'tbl_budget' AND column_name = 'financeable_flag'
  ) THEN
    ALTER TABLE landscape.tbl_budget ADD COLUMN financeable_flag BOOLEAN DEFAULT TRUE;
    RAISE NOTICE 'Added column landscape.tbl_budget.financeable_flag';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'landscape' AND table_name = 'tbl_budget' AND column_name = 'include_in_per_lot_infra_flag'
  ) THEN
    ALTER TABLE landscape.tbl_budget ADD COLUMN include_in_per_lot_infra_flag BOOLEAN DEFAULT TRUE;
    RAISE NOTICE 'Added column landscape.tbl_budget.include_in_per_lot_infra_flag';
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE schemaname = 'landscape' AND indexname = 'idx_tbl_budget_rate_profile_id'
  ) THEN
    CREATE INDEX idx_tbl_budget_rate_profile_id ON landscape.tbl_budget(rate_profile_id);
    RAISE NOTICE 'Created index idx_tbl_budget_rate_profile_id';
  END IF;
END$$;

-- ============================================================================
-- Section A: Land Acquisition
-- ============================================================================
CREATE TABLE IF NOT EXISTS landscape.financial_land_acquisition (
  land_acq_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id  BIGINT NOT NULL,
  parcel_id   BIGINT NOT NULL,
  parcel_name TEXT,
  apn         TEXT,
  city        TEXT,
  county      TEXT,
  state       TEXT,
  closure_type TEXT,
  close_date   DATE,
  option_start_date DATE,
  dd_end_date  DATE,
  gross_acres NUMERIC(12,4),
  net_usable_acres NUMERIC(12,4),
  buildable_acres NUMERIC(12,4),
  purchase_price_total NUMERIC(14,2),
  purchase_price_per_acre NUMERIC(14,2),
  broker_fee NUMERIC(14,2),
  total_closing_costs NUMERIC(14,2),
  transfer_tax NUMERIC(14,2),
  recording_fees NUMERIC(14,2),
  title_escrow_fees NUMERIC(14,2),
  environmental_reports NUMERIC(14,2),
  legal_due_diligence NUMERIC(14,2),
  other_acq_costs NUMERIC(14,2),
  earnest_money_amt NUMERIC(14,2),
  earnest_money_release_date DATE,
  option_premium_amt NUMERIC(14,2),
  option_exercise_date DATE,
  preclose_carry_tax_per_year NUMERIC(14,2),
  preclose_carry_ins_per_year NUMERIC(14,2),
  preclose_carry_other_per_year NUMERIC(14,2),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_land_acq_project ON landscape.financial_land_acquisition(project_id);
CREATE INDEX IF NOT EXISTS idx_land_acq_parcel  ON landscape.financial_land_acquisition(parcel_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_land_acq_project'
      AND conrelid = 'landscape.financial_land_acquisition'::regclass
  ) THEN
    IF EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'landscape' AND table_name = 'tbl_project'
    ) THEN
      ALTER TABLE landscape.financial_land_acquisition
        ADD CONSTRAINT fk_land_acq_project
        FOREIGN KEY (project_id) REFERENCES landscape.tbl_project(project_id) ON DELETE CASCADE;
      RAISE NOTICE 'Added FK fk_land_acq_project';
    ELSE
      RAISE NOTICE 'TODO: add FK fk_land_acq_project once landscape.tbl_project is available';
    END IF;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_land_acq_parcel'
      AND conrelid = 'landscape.financial_land_acquisition'::regclass
  ) THEN
    IF EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'landscape' AND table_name = 'project_parcel_boundaries'
    ) THEN
      ALTER TABLE landscape.financial_land_acquisition
        ADD CONSTRAINT fk_land_acq_parcel
        FOREIGN KEY (parcel_id) REFERENCES landscape.project_parcel_boundaries(parcel_id) ON DELETE CASCADE;
      RAISE NOTICE 'Added FK fk_land_acq_parcel';
    ELSE
      RAISE NOTICE 'TODO: add FK fk_land_acq_parcel once landscape.project_parcel_boundaries is available';
    END IF;
  END IF;
END$$;

-- ============================================================================
-- Section C: Overhead Tracking
-- ============================================================================
CREATE TABLE IF NOT EXISTS landscape.financial_overhead (
  overhead_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id  BIGINT NOT NULL,
  parcel_id   BIGINT NOT NULL,
  oh_code     VARCHAR(64),
  oh_category VARCHAR(64),
  description TEXT,
  allocation_method VARCHAR(32) NOT NULL,
  allocation_basis  VARCHAR(32),
  amount_input      NUMERIC(14,4),
  amount_per_event  NUMERIC(14,2),
  start_date        DATE,
  end_date          DATE,
  event_date        DATE,
  rate_profile_id   VARCHAR(64),
  capitalize_flag   BOOLEAN DEFAULT FALSE,
  financeable_flag  BOOLEAN DEFAULT FALSE,
  notes             TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_fin_oh_project ON landscape.financial_overhead(project_id);
CREATE INDEX IF NOT EXISTS idx_fin_oh_parcel  ON landscape.financial_overhead(parcel_id);
CREATE INDEX IF NOT EXISTS idx_fin_oh_method  ON landscape.financial_overhead(allocation_method);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_fin_oh_project'
      AND conrelid = 'landscape.financial_overhead'::regclass
  ) THEN
    IF EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'landscape' AND table_name = 'tbl_project'
    ) THEN
      ALTER TABLE landscape.financial_overhead
        ADD CONSTRAINT fk_fin_oh_project FOREIGN KEY (project_id)
        REFERENCES landscape.tbl_project(project_id) ON DELETE CASCADE;
      RAISE NOTICE 'Added FK fk_fin_oh_project';
    ELSE
      RAISE NOTICE 'TODO: add FK fk_fin_oh_project once landscape.tbl_project is available';
    END IF;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_fin_oh_parcel'
      AND conrelid = 'landscape.financial_overhead'::regclass
  ) THEN
    IF EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'landscape' AND table_name = 'project_parcel_boundaries'
    ) THEN
      ALTER TABLE landscape.financial_overhead
        ADD CONSTRAINT fk_fin_oh_parcel FOREIGN KEY (parcel_id)
        REFERENCES landscape.project_parcel_boundaries(parcel_id) ON DELETE CASCADE;
      RAISE NOTICE 'Added FK fk_fin_oh_parcel';
    ELSE
      RAISE NOTICE 'TODO: add FK fk_fin_oh_parcel once landscape.project_parcel_boundaries is available';
    END IF;
  END IF;
END$$;

-- ============================================================================
-- Section E: Product & Revenue Schedule
-- ============================================================================
CREATE TABLE IF NOT EXISTS landscape.tbl_revenue_schedule_res (
  revenue_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id  BIGINT NOT NULL,
  parcel_id   BIGINT NOT NULL,
  product_id  BIGINT NOT NULL,
  period_date DATE NOT NULL,
  effective_price NUMERIC(14,2),
  units_closed   INTEGER NOT NULL DEFAULT 0,
  period_revenue NUMERIC(16,2) GENERATED ALWAYS AS (effective_price * units_closed) STORED,
  avg_discount_pct NUMERIC(7,4),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (project_id, parcel_id, product_id, period_date)
);

CREATE INDEX IF NOT EXISTS idx_rev_res_project ON landscape.tbl_revenue_schedule_res(project_id);
CREATE INDEX IF NOT EXISTS idx_rev_res_parcel  ON landscape.tbl_revenue_schedule_res(parcel_id);
CREATE INDEX IF NOT EXISTS idx_rev_res_period  ON landscape.tbl_revenue_schedule_res(period_date);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_rev_res_project'
      AND conrelid = 'landscape.tbl_revenue_schedule_res'::regclass
  ) THEN
    IF EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'landscape' AND table_name = 'tbl_project'
    ) THEN
      ALTER TABLE landscape.tbl_revenue_schedule_res
        ADD CONSTRAINT fk_rev_res_project FOREIGN KEY (project_id)
        REFERENCES landscape.tbl_project(project_id) ON DELETE CASCADE;
      RAISE NOTICE 'Added FK fk_rev_res_project';
    ELSE
      RAISE NOTICE 'TODO: add FK fk_rev_res_project once landscape.tbl_project is available';
    END IF;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_rev_res_parcel'
      AND conrelid = 'landscape.tbl_revenue_schedule_res'::regclass
  ) THEN
    IF EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'landscape' AND table_name = 'project_parcel_boundaries'
    ) THEN
      ALTER TABLE landscape.tbl_revenue_schedule_res
        ADD CONSTRAINT fk_rev_res_parcel FOREIGN KEY (parcel_id)
        REFERENCES landscape.project_parcel_boundaries(parcel_id) ON DELETE CASCADE;
      RAISE NOTICE 'Added FK fk_rev_res_parcel';
    ELSE
      RAISE NOTICE 'TODO: add FK fk_rev_res_parcel once landscape.project_parcel_boundaries is available';
    END IF;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_rev_res_product'
      AND conrelid = 'landscape.tbl_revenue_schedule_res'::regclass
  ) THEN
    IF EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'landscape' AND table_name = 'res_lot_product'
    ) THEN
      ALTER TABLE landscape.tbl_revenue_schedule_res
        ADD CONSTRAINT fk_rev_res_product FOREIGN KEY (product_id)
        REFERENCES landscape.res_lot_product(product_id) ON DELETE CASCADE;
      RAISE NOTICE 'Added FK fk_rev_res_product';
    ELSE
      RAISE NOTICE 'TODO: add FK fk_rev_res_product once landscape.res_lot_product is available';
    END IF;
  END IF;
END$$;

-- ============================================================================
-- Section F: Financing & Draws
-- ============================================================================
CREATE TABLE IF NOT EXISTS landscape.financial_financing (
  financing_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id   BIGINT NOT NULL,
  parcel_id    BIGINT NOT NULL,
  financing_structure VARCHAR(32) NOT NULL,
  ltc_ratio NUMERIC(7,4),
  loan_interest_rate_annual NUMERIC(7,4),
  loan_fees_pct NUMERIC(7,4),
  equity_interest_rate_annual NUMERIC(7,4),
  loan_start_date DATE,
  loan_end_date   DATE,
  draw_method     VARCHAR(32),
  repayment_method VARCHAR(32),
  loan_term_months INTEGER,
  amortization_months INTEGER,
  idc_compound_flag BOOLEAN DEFAULT TRUE,
  idc_rate_profile_id VARCHAR(64),
  lender_name TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_financing_project ON landscape.financial_financing(project_id);
CREATE INDEX IF NOT EXISTS idx_financing_parcel  ON landscape.financial_financing(parcel_id);

CREATE TABLE IF NOT EXISTS landscape.financial_draws (
  draw_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  financing_id BIGINT NOT NULL,
  project_id   BIGINT NOT NULL,
  parcel_id    BIGINT NOT NULL,
  period_date  DATE NOT NULL,
  draw_amount       NUMERIC(16,2) DEFAULT 0,
  repayment_amount  NUMERIC(16,2) DEFAULT 0,
  idc_accrued       NUMERIC(16,2) DEFAULT 0,
  idc_capitalized   NUMERIC(16,2) DEFAULT 0,
  loan_balance_end  NUMERIC(16,2) DEFAULT 0,
  equity_balance    NUMERIC(16,2) DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (financing_id, period_date)
);

CREATE INDEX IF NOT EXISTS idx_draws_project ON landscape.financial_draws(project_id);
CREATE INDEX IF NOT EXISTS idx_draws_parcel  ON landscape.financial_draws(parcel_id);
CREATE INDEX IF NOT EXISTS idx_draws_period  ON landscape.financial_draws(period_date);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_financing_project'
      AND conrelid = 'landscape.financial_financing'::regclass
  ) THEN
    IF EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'landscape' AND table_name = 'tbl_project'
    ) THEN
      ALTER TABLE landscape.financial_financing
        ADD CONSTRAINT fk_financing_project FOREIGN KEY (project_id)
        REFERENCES landscape.tbl_project(project_id) ON DELETE CASCADE;
      RAISE NOTICE 'Added FK fk_financing_project';
    ELSE
      RAISE NOTICE 'TODO: add FK fk_financing_project once landscape.tbl_project is available';
    END IF;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_financing_parcel'
      AND conrelid = 'landscape.financial_financing'::regclass
  ) THEN
    IF EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'landscape' AND table_name = 'project_parcel_boundaries'
    ) THEN
      ALTER TABLE landscape.financial_financing
        ADD CONSTRAINT fk_financing_parcel FOREIGN KEY (parcel_id)
        REFERENCES landscape.project_parcel_boundaries(parcel_id) ON DELETE CASCADE;
      RAISE NOTICE 'Added FK fk_financing_parcel';
    ELSE
      RAISE NOTICE 'TODO: add FK fk_financing_parcel once landscape.project_parcel_boundaries is available';
    END IF;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_draws_financing'
      AND conrelid = 'landscape.financial_draws'::regclass
  ) THEN
    IF EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'landscape' AND table_name = 'financial_financing'
    ) THEN
      ALTER TABLE landscape.financial_draws
        ADD CONSTRAINT fk_draws_financing FOREIGN KEY (financing_id)
        REFERENCES landscape.financial_financing(financing_id) ON DELETE CASCADE;
      RAISE NOTICE 'Added FK fk_draws_financing';
    ELSE
      RAISE NOTICE 'TODO: add FK fk_draws_financing once landscape.financial_financing is available';
    END IF;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_draws_project'
      AND conrelid = 'landscape.financial_draws'::regclass
  ) THEN
    IF EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'landscape' AND table_name = 'tbl_project'
    ) THEN
      ALTER TABLE landscape.financial_draws
        ADD CONSTRAINT fk_draws_project FOREIGN KEY (project_id)
        REFERENCES landscape.tbl_project(project_id) ON DELETE CASCADE;
      RAISE NOTICE 'Added FK fk_draws_project';
    ELSE
      RAISE NOTICE 'TODO: add FK fk_draws_project once landscape.tbl_project is available';
    END IF;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_draws_parcel'
      AND conrelid = 'landscape.financial_draws'::regclass
  ) THEN
    IF EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'landscape' AND table_name = 'project_parcel_boundaries'
    ) THEN
      ALTER TABLE landscape.financial_draws
        ADD CONSTRAINT fk_draws_parcel FOREIGN KEY (parcel_id)
        REFERENCES landscape.project_parcel_boundaries(parcel_id) ON DELETE CASCADE;
      RAISE NOTICE 'Added FK fk_draws_parcel';
    ELSE
      RAISE NOTICE 'TODO: add FK fk_draws_parcel once landscape.project_parcel_boundaries is available';
    END IF;
  END IF;
END$$;

-- ============================================================================
-- Section G: Summary / Outputs Materialized View
-- ============================================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_matviews
    WHERE schemaname = 'landscape' AND matviewname = 'financial_summary_res'
  ) THEN
    EXECUTE $mv$
      CREATE MATERIALIZED VIEW landscape.financial_summary_res AS
      SELECT
        p.project_id,
        p.parcel_id,
        COALESCE(SUM(r.period_revenue), 0)::NUMERIC(16,2)              AS lot_revenue_total,
        COALESCE(SUM(CASE WHEN b.include_in_per_lot_infra_flag THEN b.amount ELSE 0 END), 0)::NUMERIC(16,2) AS direct_cogs_infra,
        0::NUMERIC(16,2) AS direct_cogs_land,
        0::NUMERIC(16,2) AS direct_cogs_lot_financing,
        0::NUMERIC(16,2) AS total_overhead_exp,
        COALESCE(SUM(d.idc_capitalized), 0)::NUMERIC(16,2) AS idc_total,
        now() AS snapshot_ts
      FROM (
        SELECT DISTINCT project_id, parcel_id FROM landscape.project_parcel_boundaries
      ) p
      LEFT JOIN landscape.tbl_revenue_schedule_res r
        ON r.project_id = p.project_id AND r.parcel_id = p.parcel_id
      LEFT JOIN landscape.tbl_budget b
        ON b.project_id = p.project_id AND b.parcel_id = p.parcel_id
      LEFT JOIN landscape.financial_draws d
        ON d.project_id = p.project_id AND d.parcel_id = p.parcel_id
      GROUP BY p.project_id, p.parcel_id;
    $mv$;
    RAISE NOTICE 'Created materialized view landscape.financial_summary_res';
  ELSE
    RAISE NOTICE 'Skipping creation of landscape.financial_summary_res (already exists)';
  END IF;
END$$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_matviews WHERE schemaname = 'landscape' AND matviewname = 'financial_summary_res'
  ) THEN
    IF NOT EXISTS (
      SELECT 1 FROM pg_indexes
      WHERE schemaname = 'landscape' AND indexname = 'idx_fin_summary_project_parcel'
    ) THEN
      CREATE UNIQUE INDEX idx_fin_summary_project_parcel
        ON landscape.financial_summary_res(project_id, parcel_id);
      RAISE NOTICE 'Created unique index idx_fin_summary_project_parcel';
    END IF;
  ELSE
    RAISE NOTICE 'Skipping index idx_fin_summary_project_parcel (materialized view not present)';
  END IF;
END$$;

CREATE OR REPLACE FUNCTION landscape.refresh_financial_summary_res()
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  PERFORM 1 FROM pg_matviews WHERE schemaname = 'landscape' AND matviewname = 'financial_summary_res';
  IF FOUND THEN
    REFRESH MATERIALIZED VIEW CONCURRENTLY landscape.financial_summary_res;
  ELSE
    RAISE NOTICE 'Cannot refresh landscape.financial_summary_res: materialized view does not exist';
  END IF;
END;
$$;

COMMIT;
