# Generated by Django 5.0.1 on 2025-10-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AICorrectionLog',
            fields=[
                ('correction_id', models.AutoField(primary_key=True, serialize=False)),
                ('extraction_result_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('doc_id', models.TextField(blank=True, null=True)),
                ('field_path', models.CharField(max_length=255)),
                ('ai_value', models.TextField(blank=True, null=True)),
                ('user_value', models.TextField(blank=True, null=True)),
                ('correction_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_correction_log',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DMSAssertion',
            fields=[
                ('assertion_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_id', models.TextField()),
                ('subject_type', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_ref', models.TextField(blank=True, null=True)),
                ('metric_key', models.TextField(blank=True, null=True)),
                ('value_num', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('units', models.TextField(blank=True, null=True)),
                ('context', models.CharField(blank=True, max_length=255, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('as_of_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dms_assertion',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DMSExtractQueue',
            fields=[
                ('queue_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_id', models.TextField()),
                ('extract_type', models.CharField(max_length=100)),
                ('priority', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=50)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('result_summary', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dms_extract_queue',
                'ordering': ['-priority', 'queued_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('workspace_id', models.BigIntegerField(blank=True, null=True)),
                ('phase_id', models.BigIntegerField(blank=True, null=True)),
                ('parcel_id', models.BigIntegerField(blank=True, null=True)),
                ('doc_name', models.CharField(max_length=500)),
                ('doc_type', models.CharField(default='general', max_length=100)),
                ('discipline', models.CharField(blank=True, max_length=100, null=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size_bytes', models.BigIntegerField()),
                ('sha256_hash', models.CharField(max_length=64)),
                ('storage_uri', models.TextField()),
                ('version_no', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed'), ('archived', 'Archived')], default='draft', max_length=50)),
                ('profile_json', models.JSONField(default=dict)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('priority', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_doc',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('folder_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('path', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('default_profile', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_doc_folder',
                'ordering': ['path'],
                'managed': False,
            },
        ),
    ]
