# Generated by Django 4.2.25 on 2025-11-30 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dmsextractqueue',
            options={'managed': False, 'ordering': ['-priority', 'created_at']},
        ),
    ]
