# Generated by Django 4.2.25 on 2026-02-04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_dmsextractqueue_options'),
        ('projects', '0004_add_rbac_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionCommitSnapshot',
            fields=[
                ('snapshot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=50)),
                ('committed_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot_data', models.JSONField()),
                ('changes_applied', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, db_column='doc_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_snapshots', to='documents.document')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'db_table': 'extraction_commit_snapshot',
            },
        ),
        migrations.AddIndex(
            model_name='extractioncommitsnapshot',
            index=models.Index(fields=['project', 'scope', 'is_active'], name='snapshot_project_scope_idx'),
        ),
    ]
