# Generated by Django 5.0.1 on 2026-02-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_extractioncommitsnapshot_committed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DmsDocTag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=100)),
                ('workspace_id', models.BigIntegerField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dms_doc_tags',
                'ordering': ['-usage_count', 'tag_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DmsDocTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.BigIntegerField()),
                ('assigned_by', models.IntegerField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dms_doc_tag_assignments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DmsProjectDocType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_type_name', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('is_from_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dms_project_doc_types',
                'ordering': ['display_order', 'doc_type_name'],
                'managed': False,
            },
        ),
    ]
