"""
Seed Extraction Mappings

Populates tbl_extraction_mapping with initial field mappings for AI document extraction.
Based on LANDSCAPER_DOCUMENT_EXTRACTION_DICTIONARY.md

Usage:
    python manage.py seed_extraction_mappings
    python manage.py seed_extraction_mappings --clear  # Clear existing before seeding
"""

from django.core.management.base import BaseCommand
from apps.landscaper.models import ExtractionMapping


class Command(BaseCommand):
    help = 'Seed extraction mappings for AI document extraction'

    def add_arguments(self, parser):
        parser.add_argument(
            '--clear',
            action='store_true',
            help='Clear existing system mappings before seeding',
        )

    def handle(self, *args, **options):
        if options['clear']:
            deleted_count = ExtractionMapping.objects.filter(is_system=True).delete()[0]
            self.stdout.write(f'Deleted {deleted_count} existing system mappings')

        created_count = 0
        updated_count = 0

        for mapping_data in SEED_MAPPINGS:
            mapping, created = ExtractionMapping.objects.update_or_create(
                document_type=mapping_data['document_type'],
                source_pattern=mapping_data['source_pattern'],
                target_table=mapping_data['target_table'],
                target_field=mapping_data['target_field'],
                defaults={
                    'source_aliases': mapping_data.get('source_aliases', []),
                    'data_type': mapping_data.get('data_type', 'text'),
                    'transform_rule': mapping_data.get('transform_rule'),
                    'confidence': mapping_data.get('confidence', 'Medium'),
                    'auto_write': mapping_data.get('auto_write', True),
                    'overwrite_existing': mapping_data.get('overwrite_existing', False),
                    'is_active': True,
                    'is_system': True,
                    'notes': mapping_data.get('notes'),
                }
            )
            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(self.style.SUCCESS(
            f'Seeded extraction mappings: {created_count} created, {updated_count} updated'
        ))


# ============================================================================
# SEED MAPPINGS DATA
# Based on LANDSCAPER_DOCUMENT_EXTRACTION_DICTIONARY.md
# ============================================================================

SEED_MAPPINGS = [
    # ========================================================================
    # OFFERING MEMORANDUM (OM) - Property Identification
    # ========================================================================
    {
        'document_type': 'OM',
        'source_pattern': 'Property Name',
        'source_aliases': ['Asset Name', 'Project Name'],
        'target_table': 'tbl_project',
        'target_field': 'project_name',
        'data_type': 'text',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Address',
        'source_aliases': ['Street Address', 'Property Address'],
        'target_table': 'tbl_project',
        'target_field': 'project_address',
        'data_type': 'text',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'City',
        'source_aliases': [],
        'target_table': 'tbl_project',
        'target_field': 'jurisdiction_city',
        'data_type': 'text',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'State',
        'source_aliases': [],
        'target_table': 'tbl_project',
        'target_field': 'state',
        'data_type': 'text',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Zip',
        'source_aliases': ['ZIP Code', 'Postal Code'],
        'target_table': 'tbl_project',
        'target_field': 'zip_code',
        'data_type': 'text',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'County',
        'source_aliases': [],
        'target_table': 'tbl_project',
        'target_field': 'county',
        'data_type': 'text',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'MSA',
        'source_aliases': ['Metro', 'Metropolitan Area'],
        'target_table': 'tbl_project',
        'target_field': 'msa',
        'data_type': 'text',
        'confidence': 'Medium',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Submarket',
        'source_aliases': [],
        'target_table': 'tbl_project',
        'target_field': 'submarket',
        'data_type': 'text',
        'confidence': 'Medium',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'APN',
        'source_aliases': ['Parcel Number', 'Assessor Parcel Number'],
        'target_table': 'tbl_project',
        'target_field': 'apn',
        'data_type': 'text',
        'confidence': 'High',
    },

    # ========================================================================
    # OFFERING MEMORANDUM (OM) - Physical Description
    # ========================================================================
    {
        'document_type': 'OM',
        'source_pattern': 'Year Built',
        'source_aliases': ['Built', 'Construction Year'],
        'target_table': 'tbl_project',
        'target_field': 'year_built',
        'data_type': 'integer',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Year Renovated',
        'source_aliases': ['Renovated', 'Last Renovated'],
        'target_table': 'tbl_project',
        'target_field': 'year_renovated',
        'data_type': 'integer',
        'confidence': 'Medium',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Total Units',
        'source_aliases': ['Units', 'Unit Count', 'Number of Units'],
        'target_table': 'tbl_project',
        'target_field': 'total_units',
        'data_type': 'integer',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Building SF',
        'source_aliases': ['GSF', 'Gross SF', 'Gross Building Area', 'GBA'],
        'target_table': 'tbl_project',
        'target_field': 'building_sf_gross',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'NRSF',
        'source_aliases': ['Net Rentable SF', 'NRA', 'Net Rentable Area'],
        'target_table': 'tbl_project',
        'target_field': 'building_sf_net',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Lot Size',
        'source_aliases': ['Land Area', 'Site Area'],
        'target_table': 'tbl_project',
        'target_field': 'lot_size_sf',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Acres',
        'source_aliases': ['Lot Size Acres', 'Site Acres'],
        'target_table': 'tbl_project',
        'target_field': 'acres_gross',
        'data_type': 'decimal',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Avg Unit Size',
        'source_aliases': ['Average SF', 'Avg SF', 'Average Unit Size'],
        'target_table': 'tbl_project',
        'target_field': 'avg_unit_sf',
        'data_type': 'decimal',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Stories',
        'source_aliases': ['Floors', 'Number of Stories'],
        'target_table': 'tbl_project',
        'target_field': 'stories',
        'data_type': 'integer',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Buildings',
        'source_aliases': ['Number of Buildings', 'Building Count'],
        'target_table': 'tbl_project',
        'target_field': 'building_count',
        'data_type': 'integer',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Parking Spaces',
        'source_aliases': ['Parking', 'Total Parking'],
        'target_table': 'tbl_project',
        'target_field': 'parking_spaces_total',
        'data_type': 'integer',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Parking Ratio',
        'source_aliases': [],
        'target_table': 'tbl_project',
        'target_field': 'parking_ratio',
        'data_type': 'decimal',
        'confidence': 'Medium',
    },

    # ========================================================================
    # OFFERING MEMORANDUM (OM) - Pricing & Valuation
    # ========================================================================
    {
        'document_type': 'OM',
        'source_pattern': 'Asking Price',
        'source_aliases': ['Price', 'List Price', 'Purchase Price'],
        'target_table': 'tbl_project',
        'target_field': 'asking_price',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Price/Unit',
        'source_aliases': ['Price Per Unit', '$/Unit'],
        'target_table': 'tbl_project',
        'target_field': 'price_per_unit',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Price/SF',
        'source_aliases': ['Price Per SF', '$/SF'],
        'target_table': 'tbl_project',
        'target_field': 'price_per_sf',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Cap Rate',
        'source_aliases': ['Going-In Cap Rate', 'Current Cap Rate'],
        'target_table': 'tbl_project',
        'target_field': 'cap_rate_going_in',
        'data_type': 'decimal',
        'transform_rule': 'percent_to_decimal',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Pro Forma Cap Rate',
        'source_aliases': ['Proforma Cap', 'Stabilized Cap Rate'],
        'target_table': 'tbl_project',
        'target_field': 'cap_rate_proforma',
        'data_type': 'decimal',
        'transform_rule': 'percent_to_decimal',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Exit Cap Rate',
        'source_aliases': ['Terminal Cap Rate', 'Reversion Cap'],
        'target_table': 'tbl_project',
        'target_field': 'exit_cap_rate',
        'data_type': 'decimal',
        'transform_rule': 'percent_to_decimal',
        'confidence': 'Medium',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'GRM',
        'source_aliases': ['Gross Rent Multiplier'],
        'target_table': 'tbl_project',
        'target_field': 'gross_rent_multiplier',
        'data_type': 'decimal',
        'confidence': 'Medium',
    },

    # ========================================================================
    # OFFERING MEMORANDUM (OM) - Income
    # ========================================================================
    {
        'document_type': 'OM',
        'source_pattern': 'GPR',
        'source_aliases': ['Gross Potential Rent', 'Scheduled Rent'],
        'target_table': 'tbl_project',
        'target_field': 'gross_potential_rent',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Current Rent',
        'source_aliases': ['In-Place Rent', 'Monthly Rent'],
        'target_table': 'tbl_project',
        'target_field': 'in_place_rent_monthly',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Avg Rent/Unit',
        'source_aliases': ['Average Rent', 'Avg Rent'],
        'target_table': 'tbl_project',
        'target_field': 'avg_rent_per_unit',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Market Rent',
        'source_aliases': ['Achievable Rent', 'Post-Reno Rent'],
        'target_table': 'tbl_project',
        'target_field': 'market_rent_monthly',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Loss to Lease',
        'source_aliases': ['LTL'],
        'target_table': 'tbl_project',
        'target_field': 'loss_to_lease',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Other Income',
        'source_aliases': ['Total Other Income'],
        'target_table': 'tbl_project',
        'target_field': 'other_income_total',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Parking Income',
        'source_aliases': [],
        'target_table': 'tbl_project',
        'target_field': 'parking_income',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Laundry',
        'source_aliases': ['Laundry Income', 'Vending'],
        'target_table': 'tbl_project',
        'target_field': 'laundry_income',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Pet Income',
        'source_aliases': ['Pet Fees', 'Pet Rent'],
        'target_table': 'tbl_project',
        'target_field': 'pet_income',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'Medium',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'RUBS',
        'source_aliases': ['Utility Reimbursement', 'Utility Reimb'],
        'target_table': 'tbl_project',
        'target_field': 'utility_reimbursement',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },

    # ========================================================================
    # OFFERING MEMORANDUM (OM) - Vacancy & Occupancy
    # ========================================================================
    {
        'document_type': 'OM',
        'source_pattern': 'Occupancy',
        'source_aliases': ['Occupancy Rate', 'Current Occupancy'],
        'target_table': 'tbl_project',
        'target_field': 'occupancy_rate',
        'data_type': 'decimal',
        'transform_rule': 'percent_to_decimal',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Physical Vacancy',
        'source_aliases': ['Vacancy'],
        'target_table': 'tbl_project',
        'target_field': 'physical_vacancy_pct',
        'data_type': 'decimal',
        'transform_rule': 'percent_to_decimal',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Bad Debt',
        'source_aliases': ['Collection Loss', 'Write-offs'],
        'target_table': 'tbl_project',
        'target_field': 'collection_loss_pct',
        'data_type': 'decimal',
        'transform_rule': 'percent_to_decimal',
        'confidence': 'Medium',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Concessions',
        'source_aliases': ['Concession %'],
        'target_table': 'tbl_project',
        'target_field': 'concessions_pct',
        'data_type': 'decimal',
        'transform_rule': 'percent_to_decimal',
        'confidence': 'Medium',
    },

    # ========================================================================
    # OFFERING MEMORANDUM (OM) - Operating Expenses
    # ========================================================================
    {
        'document_type': 'OM',
        'source_pattern': 'Total Operating Expenses',
        'source_aliases': ['Operating Expenses', 'OpEx', 'Total OpEx'],
        'target_table': 'tbl_project',
        'target_field': 'total_opex',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'OpEx/Unit',
        'source_aliases': ['Expenses Per Unit'],
        'target_table': 'tbl_project',
        'target_field': 'opex_per_unit',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Expense Ratio',
        'source_aliases': ['Operating Expense Ratio'],
        'target_table': 'tbl_project',
        'target_field': 'expense_ratio_pct',
        'data_type': 'decimal',
        'transform_rule': 'percent_to_decimal',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Real Estate Taxes',
        'source_aliases': ['Property Taxes', 'Taxes'],
        'target_table': 'tbl_project',
        'target_field': 'real_estate_taxes',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Insurance',
        'source_aliases': ['Property Insurance'],
        'target_table': 'tbl_project',
        'target_field': 'property_insurance',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Utilities',
        'source_aliases': ['Total Utilities'],
        'target_table': 'tbl_project',
        'target_field': 'utilities_total',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Electric',
        'source_aliases': ['Electricity'],
        'target_table': 'tbl_project',
        'target_field': 'utilities_electric',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Gas',
        'source_aliases': [],
        'target_table': 'tbl_project',
        'target_field': 'utilities_gas',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Water & Sewer',
        'source_aliases': ['Water', 'Water/Sewer'],
        'target_table': 'tbl_project',
        'target_field': 'utilities_water_sewer',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Trash',
        'source_aliases': ['Rubbish', 'Trash Removal', 'Rubbish Removal'],
        'target_table': 'tbl_project',
        'target_field': 'utilities_trash',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Management Fee',
        'source_aliases': ['Management', 'Property Management'],
        'target_table': 'tbl_project',
        'target_field': 'management_fee',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Management Fee %',
        'source_aliases': ['Management %'],
        'target_table': 'tbl_project',
        'target_field': 'management_fee_pct',
        'data_type': 'decimal',
        'transform_rule': 'percent_to_decimal',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Payroll',
        'source_aliases': ['On-Site Payroll', 'Salaries'],
        'target_table': 'tbl_project',
        'target_field': 'payroll',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Repairs & Maintenance',
        'source_aliases': ['R&M', 'Repairs'],
        'target_table': 'tbl_project',
        'target_field': 'repairs_maintenance',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Contract Services',
        'source_aliases': ['Contracted Services'],
        'target_table': 'tbl_project',
        'target_field': 'contract_services',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Administrative',
        'source_aliases': ['Admin', 'G&A'],
        'target_table': 'tbl_project',
        'target_field': 'administrative',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Marketing',
        'source_aliases': ['Advertising'],
        'target_table': 'tbl_project',
        'target_field': 'marketing',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'Medium',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Turnover',
        'source_aliases': ['Make Ready', 'Apartment Prep', 'Unit Turnover'],
        'target_table': 'tbl_project',
        'target_field': 'turnover_costs',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'Medium',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Replacement Reserves',
        'source_aliases': ['Reserves', 'CapEx Reserves'],
        'target_table': 'tbl_project',
        'target_field': 'replacement_reserves',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'Medium',
    },

    # ========================================================================
    # OFFERING MEMORANDUM (OM) - NOI & Income
    # ========================================================================
    {
        'document_type': 'OM',
        'source_pattern': 'EGI',
        'source_aliases': ['Effective Gross Income'],
        'target_table': 'tbl_project',
        'target_field': 'effective_gross_income',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'NOI',
        'source_aliases': ['Net Operating Income', 'Current NOI', 'T12 NOI'],
        'target_table': 'tbl_project',
        'target_field': 'noi_current',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Pro Forma NOI',
        'source_aliases': ['Proforma NOI', 'Stabilized NOI'],
        'target_table': 'tbl_project',
        'target_field': 'noi_proforma',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'DSCR',
        'source_aliases': ['Debt Service Coverage', 'Debt Coverage Ratio'],
        'target_table': 'tbl_project',
        'target_field': 'dscr',
        'data_type': 'decimal',
        'confidence': 'Medium',
    },

    # ========================================================================
    # OFFERING MEMORANDUM (OM) - Market Data
    # ========================================================================
    {
        'document_type': 'OM',
        'source_pattern': 'Population',
        'source_aliases': ['Market Population'],
        'target_table': 'tbl_project',
        'target_field': 'market_population',
        'data_type': 'integer',
        'transform_rule': 'extract_number',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Avg Household Income',
        'source_aliases': ['Household Income', 'Average Household Income'],
        'target_table': 'tbl_project',
        'target_field': 'market_avg_hh_income',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Median Home Value',
        'source_aliases': ['Home Value'],
        'target_table': 'tbl_project',
        'target_field': 'market_median_home_value',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Submarket Vacancy',
        'source_aliases': ['Market Vacancy'],
        'target_table': 'tbl_project',
        'target_field': 'submarket_vacancy_pct',
        'data_type': 'decimal',
        'transform_rule': 'percent_to_decimal',
        'confidence': 'High',
    },
    {
        'document_type': 'OM',
        'source_pattern': 'Submarket Rent',
        'source_aliases': ['Market Rent', 'Effective Rent'],
        'target_table': 'tbl_project',
        'target_field': 'submarket_effective_rent',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },

    # ========================================================================
    # RENT ROLL - Unit Level Data
    # ========================================================================
    {
        'document_type': 'RENT_ROLL',
        'source_pattern': 'Unit #',
        'source_aliases': ['Unit Number', 'Unit'],
        'target_table': 'tbl_multifamily_unit',
        'target_field': 'unit_number',
        'data_type': 'text',
        'confidence': 'High',
    },
    {
        'document_type': 'RENT_ROLL',
        'source_pattern': 'Unit Type',
        'source_aliases': ['Bed/Bath', 'Floor Plan'],
        'target_table': 'tbl_multifamily_unit',
        'target_field': 'unit_type',
        'data_type': 'text',
        'confidence': 'High',
    },
    {
        'document_type': 'RENT_ROLL',
        'source_pattern': 'Bedrooms',
        'source_aliases': ['BR', 'Beds'],
        'target_table': 'tbl_multifamily_unit',
        'target_field': 'bedrooms',
        'data_type': 'integer',
        'confidence': 'High',
    },
    {
        'document_type': 'RENT_ROLL',
        'source_pattern': 'Bathrooms',
        'source_aliases': ['BA', 'Baths'],
        'target_table': 'tbl_multifamily_unit',
        'target_field': 'bathrooms',
        'data_type': 'decimal',
        'confidence': 'High',
    },
    {
        'document_type': 'RENT_ROLL',
        'source_pattern': 'Square Feet',
        'source_aliases': ['SF', 'Sq Ft', 'SQFT'],
        'target_table': 'tbl_multifamily_unit',
        'target_field': 'square_feet',
        'data_type': 'integer',
        'confidence': 'High',
    },
    {
        'document_type': 'RENT_ROLL',
        'source_pattern': 'Current Rent',
        'source_aliases': ['Contract Rent', 'Monthly Rent', 'Rent'],
        'target_table': 'tbl_multifamily_unit',
        'target_field': 'current_rent',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'RENT_ROLL',
        'source_pattern': 'Market Rent',
        'source_aliases': ['Asking Rent'],
        'target_table': 'tbl_multifamily_unit',
        'target_field': 'market_rent',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'RENT_ROLL',
        'source_pattern': 'Tenant Name',
        'source_aliases': ['Resident', 'Resident Name'],
        'target_table': 'tbl_lease',
        'target_field': 'tenant_name',
        'data_type': 'text',
        'confidence': 'High',
    },
    {
        'document_type': 'RENT_ROLL',
        'source_pattern': 'Move-In Date',
        'source_aliases': ['Move In'],
        'target_table': 'tbl_lease',
        'target_field': 'move_in_date',
        'data_type': 'date',
        'transform_rule': 'parse_date',
        'confidence': 'High',
    },
    {
        'document_type': 'RENT_ROLL',
        'source_pattern': 'Lease Start',
        'source_aliases': ['Start Date', 'Lease Begin'],
        'target_table': 'tbl_lease',
        'target_field': 'lease_start_date',
        'data_type': 'date',
        'transform_rule': 'parse_date',
        'confidence': 'High',
    },
    {
        'document_type': 'RENT_ROLL',
        'source_pattern': 'Lease End',
        'source_aliases': ['Expiration', 'Lease Expiration'],
        'target_table': 'tbl_lease',
        'target_field': 'lease_end_date',
        'data_type': 'date',
        'transform_rule': 'parse_date',
        'confidence': 'High',
    },
    {
        'document_type': 'RENT_ROLL',
        'source_pattern': 'Status',
        'source_aliases': ['Occupancy Status', 'Occ Status'],
        'target_table': 'tbl_multifamily_unit',
        'target_field': 'occupancy_status',
        'data_type': 'text',
        'confidence': 'High',
    },

    # ========================================================================
    # T12 / OPERATING STATEMENT - Revenue
    # ========================================================================
    {
        'document_type': 'T12',
        'source_pattern': 'Gross Potential Rent',
        'source_aliases': ['GPR', 'Scheduled Rent'],
        'target_table': 'tbl_revenue_rent',
        'target_field': 'gross_potential_rent',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'T12',
        'source_pattern': 'Loss to Lease',
        'source_aliases': ['LTL'],
        'target_table': 'tbl_revenue_rent',
        'target_field': 'loss_to_lease',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'T12',
        'source_pattern': 'Vacancy Loss',
        'source_aliases': ['Vacancy'],
        'target_table': 'tbl_revenue_rent',
        'target_field': 'vacancy_loss',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'T12',
        'source_pattern': 'Bad Debt',
        'source_aliases': ['Write-offs', 'Collection Loss'],
        'target_table': 'tbl_revenue_rent',
        'target_field': 'bad_debt',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'T12',
        'source_pattern': 'Net Rental Income',
        'source_aliases': ['Net Rent'],
        'target_table': 'tbl_revenue_rent',
        'target_field': 'net_rental_income',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'T12',
        'source_pattern': 'Total Other Income',
        'source_aliases': ['Other Income'],
        'target_table': 'tbl_revenue_other',
        'target_field': 'other_income_total',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'T12',
        'source_pattern': 'Effective Gross Income',
        'source_aliases': ['EGI'],
        'target_table': 'tbl_project',
        'target_field': 'effective_gross_income',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },

    # ========================================================================
    # T12 / OPERATING STATEMENT - Expenses
    # ========================================================================
    {
        'document_type': 'T12',
        'source_pattern': 'Real Estate Taxes',
        'source_aliases': ['Property Taxes', 'Taxes'],
        'target_table': 'tbl_operating_expenses',
        'target_field': 'real_estate_taxes',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'T12',
        'source_pattern': 'Property Insurance',
        'source_aliases': ['Insurance'],
        'target_table': 'tbl_operating_expenses',
        'target_field': 'property_insurance',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'T12',
        'source_pattern': 'Total Utilities',
        'source_aliases': ['Utilities'],
        'target_table': 'tbl_operating_expenses',
        'target_field': 'utilities_total',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'T12',
        'source_pattern': 'Management Fee',
        'source_aliases': ['Management'],
        'target_table': 'tbl_operating_expenses',
        'target_field': 'management_fee',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'T12',
        'source_pattern': 'Payroll',
        'source_aliases': ['Payroll - Total', 'Salaries'],
        'target_table': 'tbl_operating_expenses',
        'target_field': 'payroll',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'T12',
        'source_pattern': 'Repairs & Maintenance',
        'source_aliases': ['R&M', 'Repairs'],
        'target_table': 'tbl_operating_expenses',
        'target_field': 'repairs_maintenance',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'T12',
        'source_pattern': 'Turnover',
        'source_aliases': ['Make Ready', 'Unit Turnover'],
        'target_table': 'tbl_operating_expenses',
        'target_field': 'turnover_costs',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'T12',
        'source_pattern': 'Administrative',
        'source_aliases': ['Admin', 'G&A'],
        'target_table': 'tbl_operating_expenses',
        'target_field': 'administrative',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'T12',
        'source_pattern': 'Marketing',
        'source_aliases': ['Advertising'],
        'target_table': 'tbl_operating_expenses',
        'target_field': 'marketing',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'T12',
        'source_pattern': 'Total Operating Expenses',
        'source_aliases': ['Total OpEx', 'Operating Expenses'],
        'target_table': 'tbl_operating_expenses',
        'target_field': 'total_opex',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'T12',
        'source_pattern': 'Net Operating Income',
        'source_aliases': ['NOI'],
        'target_table': 'tbl_project',
        'target_field': 'noi_t12',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },

    # ========================================================================
    # APPRAISAL - Subject Property
    # ========================================================================
    {
        'document_type': 'APPRAISAL',
        'source_pattern': 'Highest & Best Use',
        'source_aliases': ['Highest and Best Use', 'H&BU'],
        'target_table': 'tbl_valuation',
        'target_field': 'highest_best_use',
        'data_type': 'text',
        'confidence': 'High',
    },
    {
        'document_type': 'APPRAISAL',
        'source_pattern': 'Effective Age',
        'source_aliases': [],
        'target_table': 'tbl_valuation',
        'target_field': 'effective_age',
        'data_type': 'integer',
        'confidence': 'Medium',
    },
    {
        'document_type': 'APPRAISAL',
        'source_pattern': 'Remaining Economic Life',
        'source_aliases': ['Economic Life'],
        'target_table': 'tbl_valuation',
        'target_field': 'remaining_economic_life',
        'data_type': 'integer',
        'confidence': 'Medium',
    },
    {
        'document_type': 'APPRAISAL',
        'source_pattern': 'Condition Rating',
        'source_aliases': ['Condition'],
        'target_table': 'tbl_valuation',
        'target_field': 'condition_rating',
        'data_type': 'text',
        'confidence': 'High',
    },
    {
        'document_type': 'APPRAISAL',
        'source_pattern': 'Final Value Opinion',
        'source_aliases': ['Appraised Value', 'Market Value', 'Value Conclusion'],
        'target_table': 'tbl_valuation',
        'target_field': 'final_value',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'APPRAISAL',
        'source_pattern': 'Effective Date',
        'source_aliases': ['Valuation Date', 'As Of Date'],
        'target_table': 'tbl_valuation',
        'target_field': 'valuation_date',
        'data_type': 'date',
        'transform_rule': 'parse_date',
        'confidence': 'High',
    },
    {
        'document_type': 'APPRAISAL',
        'source_pattern': 'Cap Rate Selected',
        'source_aliases': ['Capitalization Rate'],
        'target_table': 'tbl_valuation',
        'target_field': 'selected_cap_rate',
        'data_type': 'decimal',
        'transform_rule': 'percent_to_decimal',
        'confidence': 'High',
    },

    # ========================================================================
    # LOAN DOCUMENTS
    # ========================================================================
    {
        'document_type': 'LOAN_DOC',
        'source_pattern': 'Loan Amount',
        'source_aliases': ['Principal', 'Loan Balance'],
        'target_table': 'tbl_debt_facility',
        'target_field': 'loan_amount',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'LOAN_DOC',
        'source_pattern': 'Interest Rate',
        'source_aliases': ['Rate', 'Note Rate'],
        'target_table': 'tbl_debt_facility',
        'target_field': 'interest_rate_pct',
        'data_type': 'decimal',
        'transform_rule': 'percent_to_decimal',
        'confidence': 'High',
    },
    {
        'document_type': 'LOAN_DOC',
        'source_pattern': 'Amortization',
        'source_aliases': ['Amortization Years', 'Amort'],
        'target_table': 'tbl_debt_facility',
        'target_field': 'amortization_years',
        'data_type': 'integer',
        'confidence': 'High',
    },
    {
        'document_type': 'LOAN_DOC',
        'source_pattern': 'Loan Term',
        'source_aliases': ['Term', 'Term Years'],
        'target_table': 'tbl_debt_facility',
        'target_field': 'loan_term_years',
        'data_type': 'integer',
        'confidence': 'High',
    },
    {
        'document_type': 'LOAN_DOC',
        'source_pattern': 'Maturity Date',
        'source_aliases': ['Maturity'],
        'target_table': 'tbl_debt_facility',
        'target_field': 'maturity_date',
        'data_type': 'date',
        'transform_rule': 'parse_date',
        'confidence': 'High',
    },
    {
        'document_type': 'LOAN_DOC',
        'source_pattern': 'LTV',
        'source_aliases': ['Loan to Value', 'LTV Ratio'],
        'target_table': 'tbl_debt_facility',
        'target_field': 'ltv_pct',
        'data_type': 'decimal',
        'transform_rule': 'percent_to_decimal',
        'confidence': 'High',
    },
    {
        'document_type': 'LOAN_DOC',
        'source_pattern': 'DSCR Requirement',
        'source_aliases': ['Required DSCR', 'Min DSCR'],
        'target_table': 'tbl_debt_facility',
        'target_field': 'dscr_required',
        'data_type': 'decimal',
        'confidence': 'High',
    },
    {
        'document_type': 'LOAN_DOC',
        'source_pattern': 'Lender',
        'source_aliases': ['Lender Name', 'Bank'],
        'target_table': 'tbl_debt_facility',
        'target_field': 'lender_name',
        'data_type': 'text',
        'confidence': 'High',
    },

    # ========================================================================
    # PSA - Purchase Agreement
    # ========================================================================
    {
        'document_type': 'PSA',
        'source_pattern': 'Purchase Price',
        'source_aliases': ['Price', 'Contract Price'],
        'target_table': 'tbl_property_acquisition',
        'target_field': 'purchase_price',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'PSA',
        'source_pattern': 'Earnest Money',
        'source_aliases': ['Deposit', 'EMD'],
        'target_table': 'tbl_property_acquisition',
        'target_field': 'earnest_money',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'PSA',
        'source_pattern': 'Due Diligence Period',
        'source_aliases': ['Inspection Period', 'DD Period'],
        'target_table': 'tbl_property_acquisition',
        'target_field': 'due_diligence_days',
        'data_type': 'integer',
        'confidence': 'High',
    },
    {
        'document_type': 'PSA',
        'source_pattern': 'Closing Date',
        'source_aliases': ['Close Date', 'Scheduled Closing'],
        'target_table': 'tbl_property_acquisition',
        'target_field': 'scheduled_closing_date',
        'data_type': 'date',
        'transform_rule': 'parse_date',
        'confidence': 'High',
    },
    {
        'document_type': 'PSA',
        'source_pattern': 'Buyer',
        'source_aliases': ['Buyer Entity', 'Purchaser'],
        'target_table': 'tbl_property_acquisition',
        'target_field': 'buyer_name',
        'data_type': 'text',
        'confidence': 'High',
    },
    {
        'document_type': 'PSA',
        'source_pattern': 'Seller',
        'source_aliases': ['Seller Entity'],
        'target_table': 'tbl_property_acquisition',
        'target_field': 'seller_name',
        'data_type': 'text',
        'confidence': 'High',
    },

    # ========================================================================
    # ZONING LETTER
    # ========================================================================
    {
        'document_type': 'ZONING',
        'source_pattern': 'Zoning Classification',
        'source_aliases': ['Zoning', 'Zone'],
        'target_table': 'tbl_project',
        'target_field': 'current_zoning',
        'data_type': 'text',
        'confidence': 'High',
    },
    {
        'document_type': 'ZONING',
        'source_pattern': 'General Plan',
        'source_aliases': ['General Plan Designation', 'Land Use'],
        'target_table': 'tbl_project',
        'target_field': 'general_plan_designation',
        'data_type': 'text',
        'confidence': 'High',
    },
    {
        'document_type': 'ZONING',
        'source_pattern': 'Max Density',
        'source_aliases': ['Density', 'DU/AC'],
        'target_table': 'tbl_entitlement',
        'target_field': 'max_density_allowed',
        'data_type': 'decimal',
        'confidence': 'High',
    },
    {
        'document_type': 'ZONING',
        'source_pattern': 'Max Height',
        'source_aliases': ['Height Limit', 'Building Height'],
        'target_table': 'tbl_entitlement',
        'target_field': 'max_height_ft',
        'data_type': 'decimal',
        'confidence': 'High',
    },
    {
        'document_type': 'ZONING',
        'source_pattern': 'Max FAR',
        'source_aliases': ['FAR', 'Floor Area Ratio'],
        'target_table': 'tbl_entitlement',
        'target_field': 'max_far',
        'data_type': 'decimal',
        'confidence': 'High',
    },

    # ========================================================================
    # TAX BILL
    # ========================================================================
    {
        'document_type': 'TAX_BILL',
        'source_pattern': 'Assessed Value',
        'source_aliases': ['Total Assessed Value'],
        'target_table': 'tbl_tax_assessment',
        'target_field': 'assessed_value_total',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'TAX_BILL',
        'source_pattern': 'Annual Tax Amount',
        'source_aliases': ['Tax Amount', 'Annual Taxes'],
        'target_table': 'tbl_operating_expenses',
        'target_field': 'real_estate_taxes',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'TAX_BILL',
        'source_pattern': 'Tax Rate',
        'source_aliases': ['Mill Rate', 'Tax %'],
        'target_table': 'tbl_tax_assessment',
        'target_field': 'tax_rate_pct',
        'data_type': 'decimal',
        'transform_rule': 'percent_to_decimal',
        'confidence': 'High',
    },

    # ========================================================================
    # INSURANCE
    # ========================================================================
    {
        'document_type': 'INSURANCE',
        'source_pattern': 'Annual Premium',
        'source_aliases': ['Premium'],
        'target_table': 'tbl_operating_expenses',
        'target_field': 'property_insurance',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'INSURANCE',
        'source_pattern': 'Coverage - Property',
        'source_aliases': ['Property Coverage', 'Building Coverage'],
        'target_table': 'tbl_insurance',
        'target_field': 'coverage_property',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'INSURANCE',
        'source_pattern': 'Coverage - Liability',
        'source_aliases': ['Liability Coverage', 'GL Coverage'],
        'target_table': 'tbl_insurance',
        'target_field': 'coverage_liability',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },

    # ========================================================================
    # MARKET STUDY
    # ========================================================================
    {
        'document_type': 'MARKET_STUDY',
        'source_pattern': 'Submarket Name',
        'source_aliases': ['Submarket'],
        'target_table': 'tbl_market_data',
        'target_field': 'submarket_name',
        'data_type': 'text',
        'confidence': 'High',
    },
    {
        'document_type': 'MARKET_STUDY',
        'source_pattern': 'Vacancy Rate',
        'source_aliases': ['Market Vacancy', 'Submarket Vacancy'],
        'target_table': 'tbl_market_data',
        'target_field': 'submarket_vacancy_pct',
        'data_type': 'decimal',
        'transform_rule': 'percent_to_decimal',
        'confidence': 'High',
    },
    {
        'document_type': 'MARKET_STUDY',
        'source_pattern': 'Effective Rent',
        'source_aliases': ['Market Rent', 'Submarket Rent'],
        'target_table': 'tbl_market_data',
        'target_field': 'submarket_effective_rent',
        'data_type': 'decimal',
        'transform_rule': 'strip_currency',
        'confidence': 'High',
    },
    {
        'document_type': 'MARKET_STUDY',
        'source_pattern': 'Rent Growth',
        'source_aliases': ['Rent Growth YoY', 'Annual Rent Growth'],
        'target_table': 'tbl_market_data',
        'target_field': 'submarket_rent_growth_yoy',
        'data_type': 'decimal',
        'transform_rule': 'percent_to_decimal',
        'confidence': 'High',
    },
    {
        'document_type': 'MARKET_STUDY',
        'source_pattern': 'Under Construction',
        'source_aliases': ['Pipeline', 'Supply Pipeline'],
        'target_table': 'tbl_market_data',
        'target_field': 'submarket_under_construction',
        'data_type': 'integer',
        'confidence': 'Medium',
    },
]
