# Generated by Django 5.0.1 on 2025-11-20 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_userpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.CharField(help_text='Format: msg_{timestamp}_{random4}', max_length=100, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], help_text='Message sender: user or assistant', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When message was created')),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata (e.g., confidence scores, suggestions)', null=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='landscaper_messages', to='projects.project')),
                ('user', models.ForeignKey(blank=True, help_text='User who sent the message (null for assistant messages)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'landscape"."landscaper_chat_message',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LandscaperAdvice',
            fields=[
                ('advice_id', models.AutoField(primary_key=True, serialize=False)),
                ('assumption_key', models.CharField(help_text='Key identifying the assumption (e.g., land_price_per_acre, grading_cost_per_sf)', max_length=100)),
                ('lifecycle_stage', models.CharField(help_text='Development stage (e.g., ACQUISITION, PLANNING, CONSTRUCTION)', max_length=50)),
                ('suggested_value', models.DecimalField(decimal_places=4, help_text='AI-suggested value for the assumption', max_digits=15)),
                ('confidence_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('placeholder', 'Placeholder')], help_text='AI confidence in this suggestion', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When advice was generated')),
                ('notes', models.TextField(blank=True, help_text='Additional context or reasoning for the suggestion', null=True)),
                ('message', models.ForeignKey(blank=True, db_column='message_id', help_text='Chat message that generated this advice', null=True, on_delete=django.db.models.deletion.CASCADE, to='landscaper.chatmessage')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='landscaper_advice', to='projects.project')),
            ],
            options={
                'verbose_name': 'Landscaper Advice',
                'verbose_name_plural': 'Landscaper Advice',
                'db_table': 'landscape"."landscaper_advice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['project', 'timestamp'], name='landscaper__project_0fbb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['timestamp'], name='landscaper__timesta_8945c8_idx'),
        ),
        migrations.AddIndex(
            model_name='landscaperadvice',
            index=models.Index(fields=['project', 'assumption_key'], name='landscaper__project_948878_idx'),
        ),
        migrations.AddIndex(
            model_name='landscaperadvice',
            index=models.Index(fields=['project', 'lifecycle_stage'], name='landscaper__project_e8f509_idx'),
        ),
        migrations.AddIndex(
            model_name='landscaperadvice',
            index=models.Index(fields=['created_at'], name='landscaper__created_57ae5a_idx'),
        ),
    ]
