# Generated by Django 5.0.1 on 2026-02-25 01:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_intelligence_tables'),
        ('landscaper', '0001_initial'),
        ('projects', '0006_intelligence_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_context', models.CharField(choices=[('home', 'Home'), ('property', 'Property'), ('operations', 'Operations'), ('feasibility', 'Feasibility'), ('capitalization', 'Capitalization'), ('reports', 'Reports'), ('documents', 'Documents')], help_text='Folder/page context: home, property, operations, etc.', max_length=50)),
                ('subtab_context', models.CharField(blank=True, help_text='Optional subtab context for finer granularity (reserved for future)', max_length=50, null=True)),
                ('title', models.CharField(blank=True, help_text='Thread title, auto-generated after first AI response, user-editable', max_length=255, null=True)),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary for cross-thread RAG retrieval', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this thread is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When thread was closed (user started new or idle timeout)', null=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='projects.project')),
            ],
            options={
                'verbose_name': 'Chat Thread',
                'verbose_name_plural': 'Chat Threads',
                'db_table': 'landscape"."landscaper_chat_thread',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(help_text='Type of document this mapping applies to (from DMS templates)', max_length=50)),
                ('source_pattern', models.CharField(help_text='Label or pattern to look for in documents', max_length=200)),
                ('source_aliases', models.JSONField(blank=True, default=list, help_text='Additional patterns that map to the same field', null=True)),
                ('target_table', models.CharField(help_text='Database table name (e.g., tbl_project)', max_length=100)),
                ('target_field', models.CharField(help_text='Database field name (e.g., year_built)', max_length=100)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('json', 'JSON')], default='text', help_text='Data type for the extracted value', max_length=20)),
                ('transform_rule', models.CharField(blank=True, choices=[('none', 'None'), ('strip_currency', 'Strip Currency'), ('percent_to_decimal', 'Percent to Decimal'), ('parse_date', 'Parse Date'), ('extract_number', 'Extract Number')], help_text='Transformation to apply to extracted value', max_length=100, null=True)),
                ('confidence', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', help_text='Extraction confidence level', max_length=10)),
                ('auto_write', models.BooleanField(default=True, help_text='Automatically write to database on extraction')),
                ('overwrite_existing', models.BooleanField(default=False, help_text='Overwrite existing values when extracting')),
                ('applicable_tags', models.JSONField(blank=True, default=list, help_text='When set, mapping only fires for documents with matching tags. Empty = all docs of this Doc Type.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this mapping is active')),
                ('is_system', models.BooleanField(default=True, help_text='System mappings cannot be deleted')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this mapping', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_mappings_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_mappings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extraction Mapping',
                'verbose_name_plural': 'Extraction Mappings',
                'db_table': 'landscape"."tbl_extraction_mapping',
                'ordering': ['document_type', 'source_pattern'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_id', models.IntegerField(blank=True, help_text='Document ID that was extracted from', null=True)),
                ('source_pattern_matched', models.CharField(blank=True, help_text='Actual pattern that matched', max_length=200, null=True)),
                ('extracted_value', models.TextField(blank=True, help_text='Raw value extracted from document', null=True)),
                ('transformed_value', models.TextField(blank=True, help_text='Value after transformation', null=True)),
                ('previous_value', models.TextField(blank=True, help_text='Previous value in database before extraction', null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, help_text='Confidence score (0-1)', max_digits=5, null=True)),
                ('extraction_context', models.TextField(blank=True, help_text='Surrounding text for debugging', null=True)),
                ('was_written', models.BooleanField(default=False, help_text='Whether the value was written to database')),
                ('was_accepted', models.BooleanField(blank=True, help_text='NULL=pending, True=accepted, False=rejected', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if rejected', null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When extraction was reviewed', null=True)),
                ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraction_logs', to='projects.project')),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_reviews', to=settings.AUTH_USER_MODEL)),
                ('mapping', models.ForeignKey(blank=True, db_column='mapping_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_logs', to='landscaper.extractionmapping')),
            ],
            options={
                'verbose_name': 'Extraction Log',
                'verbose_name_plural': 'Extraction Logs',
                'db_table': 'landscape"."tbl_extraction_log',
                'ordering': ['-extracted_at'],
            },
        ),
        migrations.CreateModel(
            name='IntakeSession',
            fields=[
                ('intake_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('intake_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='External-facing UUID for API URLs', unique=True)),
                ('document_type', models.CharField(blank=True, help_text='Document type classification (OM, T-12, Rent Roll, etc.)', max_length=50, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('mapping_complete', 'Mapping Complete'), ('values_complete', 'Values Complete'), ('committed', 'Committed'), ('abandoned', 'Abandoned')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('doc', models.ForeignKey(blank=True, db_column='doc_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_sessions', to='documents.document')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='intake_sessions', to='projects.project')),
            ],
            options={
                'verbose_name': 'Intake Session',
                'verbose_name_plural': 'Intake Sessions',
                'db_table': 'landscape"."tbl_intake_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelOverride',
            fields=[
                ('override_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('division_id', models.BigIntegerField(blank=True, help_text='FK to tbl_division.division_id (no ORM model exists)', null=True)),
                ('unit_id', models.IntegerField(blank=True, help_text='FK to tbl_multifamily_unit.unit_id', null=True)),
                ('field_key', models.CharField(help_text='Field registry key being overridden', max_length=100)),
                ('calculated_value', models.TextField(blank=True, help_text='The platform-calculated value at time of override', null=True)),
                ('override_value', models.TextField(help_text='The user-specified override value')),
                ('is_active', models.BooleanField(default=True, help_text='True = override active; False = reverted to calculated')),
                ('toggled_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='model_overrides', to='projects.project')),
                ('toggled_by', models.ForeignKey(blank=True, db_column='toggled_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_overrides_toggled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model Override',
                'verbose_name_plural': 'Model Overrides',
                'db_table': 'landscape"."tbl_model_override',
                'ordering': ['-toggled_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], help_text='Message sender: user or assistant', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('metadata', models.JSONField(blank=True, help_text='Additional data: tool calls, sources, mutation proposals, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(db_column='thread_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='landscaper.chatthread')),
            ],
            options={
                'verbose_name': 'Thread Message',
                'verbose_name_plural': 'Thread Messages',
                'db_table': 'landscape"."landscaper_thread_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.IntegerField(help_text='Denormalized project_id for faster queries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(db_column='thread_id', on_delete=django.db.models.deletion.CASCADE, related_name='message_embeddings', to='landscaper.chatthread')),
                ('message', models.ForeignKey(db_column='message_id', on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='landscaper.threadmessage')),
            ],
            options={
                'verbose_name': 'Chat Embedding',
                'verbose_name_plural': 'Chat Embeddings',
                'db_table': 'landscape"."landscaper_chat_embedding',
            },
        ),
        migrations.CreateModel(
            name='ActivityItem',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('status', 'Status'), ('decision', 'Decision'), ('update', 'Update'), ('alert', 'Alert')], help_text='Type of activity: status, decision, update, alert', max_length=20)),
                ('title', models.CharField(help_text='Short title for the activity (e.g., "Market Analysis")', max_length=100)),
                ('summary', models.TextField(help_text='Brief summary of the activity status')),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial'), ('blocked', 'Blocked'), ('pending', 'Pending')], default='pending', help_text='Activity status: complete, partial, blocked, pending', max_length=20)),
                ('confidence', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), (None, 'N/A')], help_text='Confidence level for this data', max_length=20, null=True)),
                ('link', models.CharField(blank=True, help_text='Navigation link relative to project (e.g., /market)', max_length=255, null=True)),
                ('blocked_by', models.TextField(blank=True, help_text='What is blocking this activity', null=True)),
                ('details', models.JSONField(blank=True, help_text='Additional details as a list of strings', null=True)),
                ('highlight_fields', models.JSONField(blank=True, help_text='List of field names to highlight when navigating', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether user has viewed this activity')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When activity was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When activity was last updated')),
                ('source_type', models.CharField(blank=True, help_text='Source of activity: document, budget, market, ai_analysis', max_length=50, null=True)),
                ('source_id', models.CharField(blank=True, help_text='Reference ID to source record', max_length=100, null=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='landscaper_activities', to='projects.project')),
            ],
            options={
                'verbose_name': 'Activity Item',
                'verbose_name_plural': 'Activity Items',
                'db_table': 'landscape"."landscaper_activity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='landscaper__project_8a480e_idx'), models.Index(fields=['project', 'is_read'], name='landscaper__project_127687_idx'), models.Index(fields=['source_type', 'source_id'], name='landscaper__source__712230_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['project'], name='landscaper__project_efd964_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['project', 'page_context'], name='landscaper__project_317b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['project', 'is_active'], name='landscaper__project_572cee_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['project', '-updated_at'], name='landscaper__project_97dc81_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='extractionmapping',
            unique_together={('document_type', 'source_pattern', 'target_table', 'target_field')},
        ),
        migrations.AddIndex(
            model_name='extractionlog',
            index=models.Index(fields=['mapping'], name='tbl_extract_mapping_819a26_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionlog',
            index=models.Index(fields=['project'], name='tbl_extract_project_45b6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionlog',
            index=models.Index(fields=['doc_id'], name='tbl_extract_doc_id_4191e3_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionlog',
            index=models.Index(fields=['extracted_at'], name='tbl_extract_extract_f31dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='threadmessage',
            index=models.Index(fields=['thread'], name='landscaper__thread__001166_idx'),
        ),
        migrations.AddIndex(
            model_name='threadmessage',
            index=models.Index(fields=['thread', 'created_at'], name='landscaper__thread__ae4edd_idx'),
        ),
        migrations.AddIndex(
            model_name='chatembedding',
            index=models.Index(fields=['project_id'], name='landscaper__project_b24d76_idx'),
        ),
        migrations.AddIndex(
            model_name='chatembedding',
            index=models.Index(fields=['thread'], name='landscaper__thread__a4bf47_idx'),
        ),
    ]
