# Generated by Django 5.0.1 on 2026-02-25 01:29
# Modified: Made idempotent with CREATE TABLE IF NOT EXISTS for Railway deployment
# (tables were previously created via raw SQL before Django migration state existed)

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_intelligence_tables'),
        ('landscaper', '0001_initial'),
        ('projects', '0006_intelligence_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── ChatThread ──────────────────────────────────────────────
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS landscape.landscaper_chat_thread (
                    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
                    project_id INTEGER NOT NULL REFERENCES landscape.tbl_project(project_id) ON DELETE CASCADE,
                    page_context VARCHAR(50) NOT NULL,
                    subtab_context VARCHAR(50),
                    title VARCHAR(255),
                    summary TEXT,
                    is_active BOOLEAN DEFAULT TRUE,
                    created_at TIMESTAMPTZ DEFAULT NOW(),
                    updated_at TIMESTAMPTZ DEFAULT NOW(),
                    closed_at TIMESTAMPTZ
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS landscape.landscaper_chat_thread CASCADE;",
            state_operations=[
                migrations.CreateModel(
                    name='ChatThread',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('page_context', models.CharField(choices=[('home', 'Home'), ('property', 'Property'), ('operations', 'Operations'), ('feasibility', 'Feasibility'), ('capitalization', 'Capitalization'), ('reports', 'Reports'), ('documents', 'Documents')], help_text='Folder/page context: home, property, operations, etc.', max_length=50)),
                        ('subtab_context', models.CharField(blank=True, help_text='Optional subtab context for finer granularity (reserved for future)', max_length=50, null=True)),
                        ('title', models.CharField(blank=True, help_text='Thread title, auto-generated after first AI response, user-editable', max_length=255, null=True)),
                        ('summary', models.TextField(blank=True, help_text='AI-generated summary for cross-thread RAG retrieval', null=True)),
                        ('is_active', models.BooleanField(default=True, help_text='Whether this thread is currently active')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('closed_at', models.DateTimeField(blank=True, help_text='When thread was closed (user started new or idle timeout)', null=True)),
                        ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='projects.project')),
                    ],
                    options={
                        'verbose_name': 'Chat Thread',
                        'verbose_name_plural': 'Chat Threads',
                        'db_table': 'landscape"."landscaper_chat_thread',
                        'ordering': ['-updated_at'],
                    },
                ),
            ],
        ),

        # ── ExtractionMapping ───────────────────────────────────────
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS landscape.tbl_extraction_mapping (
                    mapping_id SERIAL PRIMARY KEY,
                    document_type VARCHAR(50) NOT NULL,
                    source_pattern VARCHAR(200) NOT NULL,
                    source_aliases JSONB,
                    target_table VARCHAR(100) NOT NULL,
                    target_field VARCHAR(100) NOT NULL,
                    data_type VARCHAR(20) NOT NULL DEFAULT 'text',
                    transform_rule VARCHAR(100),
                    confidence VARCHAR(10) NOT NULL DEFAULT 'Medium',
                    auto_write BOOLEAN NOT NULL DEFAULT TRUE,
                    overwrite_existing BOOLEAN NOT NULL DEFAULT FALSE,
                    is_active BOOLEAN NOT NULL DEFAULT TRUE,
                    is_system BOOLEAN NOT NULL DEFAULT TRUE,
                    notes TEXT,
                    created_by INTEGER REFERENCES landscape.auth_user(id) ON DELETE SET NULL,
                    created_at TIMESTAMPTZ DEFAULT NOW(),
                    updated_by INTEGER REFERENCES landscape.auth_user(id) ON DELETE SET NULL,
                    updated_at TIMESTAMPTZ DEFAULT NOW(),
                    applicable_tags JSONB DEFAULT '[]'::JSONB
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS landscape.tbl_extraction_mapping CASCADE;",
            state_operations=[
                migrations.CreateModel(
                    name='ExtractionMapping',
                    fields=[
                        ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                        ('document_type', models.CharField(help_text='Type of document this mapping applies to (from DMS templates)', max_length=50)),
                        ('source_pattern', models.CharField(help_text='Label or pattern to look for in documents', max_length=200)),
                        ('source_aliases', models.JSONField(blank=True, default=list, help_text='Additional patterns that map to the same field', null=True)),
                        ('target_table', models.CharField(help_text='Database table name (e.g., tbl_project)', max_length=100)),
                        ('target_field', models.CharField(help_text='Database field name (e.g., year_built)', max_length=100)),
                        ('data_type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('json', 'JSON')], default='text', help_text='Data type for the extracted value', max_length=20)),
                        ('transform_rule', models.CharField(blank=True, choices=[('none', 'None'), ('strip_currency', 'Strip Currency'), ('percent_to_decimal', 'Percent to Decimal'), ('parse_date', 'Parse Date'), ('extract_number', 'Extract Number')], help_text='Transformation to apply to extracted value', max_length=100, null=True)),
                        ('confidence', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', help_text='Extraction confidence level', max_length=10)),
                        ('auto_write', models.BooleanField(default=True, help_text='Automatically write to database on extraction')),
                        ('overwrite_existing', models.BooleanField(default=False, help_text='Overwrite existing values when extracting')),
                        ('applicable_tags', models.JSONField(blank=True, default=list, help_text='When set, mapping only fires for documents with matching tags. Empty = all docs of this Doc Type.')),
                        ('is_active', models.BooleanField(default=True, help_text='Whether this mapping is active')),
                        ('is_system', models.BooleanField(default=True, help_text='System mappings cannot be deleted')),
                        ('notes', models.TextField(blank=True, help_text='Additional notes about this mapping', null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_mappings_created', to=settings.AUTH_USER_MODEL)),
                        ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_mappings_updated', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Extraction Mapping',
                        'verbose_name_plural': 'Extraction Mappings',
                        'db_table': 'landscape"."tbl_extraction_mapping',
                        'ordering': ['document_type', 'source_pattern'],
                    },
                ),
            ],
        ),

        # ── ExtractionLog ───────────────────────────────────────────
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS landscape.tbl_extraction_log (
                    log_id SERIAL PRIMARY KEY,
                    mapping_id INTEGER REFERENCES landscape.tbl_extraction_mapping(mapping_id) ON DELETE SET NULL,
                    project_id INTEGER,
                    doc_id INTEGER,
                    source_pattern_matched VARCHAR(200),
                    extracted_value TEXT,
                    transformed_value TEXT,
                    previous_value TEXT,
                    confidence_score NUMERIC(5,4),
                    extraction_context TEXT,
                    was_written BOOLEAN NOT NULL DEFAULT FALSE,
                    was_accepted BOOLEAN,
                    rejection_reason TEXT,
                    extracted_at TIMESTAMPTZ DEFAULT NOW(),
                    reviewed_at TIMESTAMPTZ,
                    reviewed_by INTEGER REFERENCES landscape.auth_user(id) ON DELETE SET NULL
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS landscape.tbl_extraction_log CASCADE;",
            state_operations=[
                migrations.CreateModel(
                    name='ExtractionLog',
                    fields=[
                        ('log_id', models.AutoField(primary_key=True, serialize=False)),
                        ('doc_id', models.IntegerField(blank=True, help_text='Document ID that was extracted from', null=True)),
                        ('source_pattern_matched', models.CharField(blank=True, help_text='Actual pattern that matched', max_length=200, null=True)),
                        ('extracted_value', models.TextField(blank=True, help_text='Raw value extracted from document', null=True)),
                        ('transformed_value', models.TextField(blank=True, help_text='Value after transformation', null=True)),
                        ('previous_value', models.TextField(blank=True, help_text='Previous value in database before extraction', null=True)),
                        ('confidence_score', models.DecimalField(blank=True, decimal_places=4, help_text='Confidence score (0-1)', max_digits=5, null=True)),
                        ('extraction_context', models.TextField(blank=True, help_text='Surrounding text for debugging', null=True)),
                        ('was_written', models.BooleanField(default=False, help_text='Whether the value was written to database')),
                        ('was_accepted', models.BooleanField(blank=True, help_text='NULL=pending, True=accepted, False=rejected', null=True)),
                        ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if rejected', null=True)),
                        ('extracted_at', models.DateTimeField(auto_now_add=True)),
                        ('reviewed_at', models.DateTimeField(blank=True, help_text='When extraction was reviewed', null=True)),
                        ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraction_logs', to='projects.project')),
                        ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_reviews', to=settings.AUTH_USER_MODEL)),
                        ('mapping', models.ForeignKey(blank=True, db_column='mapping_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_logs', to='landscaper.extractionmapping')),
                    ],
                    options={
                        'verbose_name': 'Extraction Log',
                        'verbose_name_plural': 'Extraction Logs',
                        'db_table': 'landscape"."tbl_extraction_log',
                        'ordering': ['-extracted_at'],
                    },
                ),
            ],
        ),

        # ── IntakeSession ───────────────────────────────────────────
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS landscape.tbl_intake_session (
                    intake_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                    intake_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
                    project_id INTEGER NOT NULL REFERENCES landscape.tbl_project(project_id) ON DELETE CASCADE,
                    doc_id BIGINT REFERENCES landscape.core_doc(doc_id) ON DELETE SET NULL,
                    document_type VARCHAR(50),
                    status VARCHAR(30) NOT NULL DEFAULT 'draft'
                        CHECK (status IN ('draft','mapping_complete','values_complete','committed','abandoned')),
                    created_by INTEGER REFERENCES landscape.auth_user(id) ON DELETE SET NULL,
                    created_at TIMESTAMPTZ DEFAULT NOW(),
                    updated_at TIMESTAMPTZ DEFAULT NOW()
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS landscape.tbl_intake_session CASCADE;",
            state_operations=[
                migrations.CreateModel(
                    name='IntakeSession',
                    fields=[
                        ('intake_id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('intake_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='External-facing UUID for API URLs', unique=True)),
                        ('document_type', models.CharField(blank=True, help_text='Document type classification (OM, T-12, Rent Roll, etc.)', max_length=50, null=True)),
                        ('status', models.CharField(choices=[('draft', 'Draft'), ('mapping_complete', 'Mapping Complete'), ('values_complete', 'Values Complete'), ('committed', 'Committed'), ('abandoned', 'Abandoned')], default='draft', max_length=30)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_sessions_created', to=settings.AUTH_USER_MODEL)),
                        ('doc', models.ForeignKey(blank=True, db_column='doc_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_sessions', to='documents.document')),
                        ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='intake_sessions', to='projects.project')),
                    ],
                    options={
                        'verbose_name': 'Intake Session',
                        'verbose_name_plural': 'Intake Sessions',
                        'db_table': 'landscape"."tbl_intake_session',
                        'ordering': ['-created_at'],
                    },
                ),
            ],
        ),

        # ── ModelOverride ───────────────────────────────────────────
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS landscape.tbl_model_override (
                    override_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                    project_id INTEGER NOT NULL REFERENCES landscape.tbl_project(project_id) ON DELETE CASCADE,
                    division_id BIGINT REFERENCES landscape.tbl_division(division_id) ON DELETE CASCADE,
                    unit_id INTEGER REFERENCES landscape.tbl_multifamily_unit(unit_id) ON DELETE CASCADE,
                    field_key VARCHAR(100) NOT NULL,
                    calculated_value TEXT,
                    override_value TEXT NOT NULL,
                    is_active BOOLEAN NOT NULL DEFAULT TRUE,
                    toggled_by INTEGER REFERENCES landscape.auth_user(id) ON DELETE SET NULL,
                    toggled_at TIMESTAMPTZ DEFAULT NOW()
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS landscape.tbl_model_override CASCADE;",
            state_operations=[
                migrations.CreateModel(
                    name='ModelOverride',
                    fields=[
                        ('override_id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('division_id', models.BigIntegerField(blank=True, help_text='FK to tbl_division.division_id (no ORM model exists)', null=True)),
                        ('unit_id', models.IntegerField(blank=True, help_text='FK to tbl_multifamily_unit.unit_id', null=True)),
                        ('field_key', models.CharField(help_text='Field registry key being overridden', max_length=100)),
                        ('calculated_value', models.TextField(blank=True, help_text='The platform-calculated value at time of override', null=True)),
                        ('override_value', models.TextField(help_text='The user-specified override value')),
                        ('is_active', models.BooleanField(default=True, help_text='True = override active; False = reverted to calculated')),
                        ('toggled_at', models.DateTimeField(auto_now=True)),
                        ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='model_overrides', to='projects.project')),
                        ('toggled_by', models.ForeignKey(blank=True, db_column='toggled_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_overrides_toggled', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Model Override',
                        'verbose_name_plural': 'Model Overrides',
                        'db_table': 'landscape"."tbl_model_override',
                        'ordering': ['-toggled_at'],
                    },
                ),
            ],
        ),

        # ── ThreadMessage ───────────────────────────────────────────
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS landscape.landscaper_thread_message (
                    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
                    thread_id UUID NOT NULL REFERENCES landscape.landscaper_chat_thread(id) ON DELETE CASCADE,
                    role VARCHAR(20) NOT NULL
                        CHECK (role IN ('user','assistant')),
                    content TEXT NOT NULL,
                    metadata JSONB,
                    created_at TIMESTAMPTZ DEFAULT NOW()
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS landscape.landscaper_thread_message CASCADE;",
            state_operations=[
                migrations.CreateModel(
                    name='ThreadMessage',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], help_text='Message sender: user or assistant', max_length=20)),
                        ('content', models.TextField(help_text='Message content')),
                        ('metadata', models.JSONField(blank=True, help_text='Additional data: tool calls, sources, mutation proposals, etc.', null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('thread', models.ForeignKey(db_column='thread_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='landscaper.chatthread')),
                    ],
                    options={
                        'verbose_name': 'Thread Message',
                        'verbose_name_plural': 'Thread Messages',
                        'db_table': 'landscape"."landscaper_thread_message',
                        'ordering': ['created_at'],
                    },
                ),
            ],
        ),

        # ── ChatEmbedding ──────────────────────────────────────────
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS landscape.landscaper_chat_embedding (
                    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
                    message_id UUID NOT NULL REFERENCES landscape.landscaper_thread_message(id) ON DELETE CASCADE,
                    thread_id UUID NOT NULL REFERENCES landscape.landscaper_chat_thread(id) ON DELETE CASCADE,
                    project_id INTEGER NOT NULL,
                    embedding VECTOR(1536),
                    created_at TIMESTAMPTZ DEFAULT NOW()
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS landscape.landscaper_chat_embedding CASCADE;",
            state_operations=[
                migrations.CreateModel(
                    name='ChatEmbedding',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('project_id', models.IntegerField(help_text='Denormalized project_id for faster queries')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('thread', models.ForeignKey(db_column='thread_id', on_delete=django.db.models.deletion.CASCADE, related_name='message_embeddings', to='landscaper.chatthread')),
                        ('message', models.ForeignKey(db_column='message_id', on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='landscaper.threadmessage')),
                    ],
                    options={
                        'verbose_name': 'Chat Embedding',
                        'verbose_name_plural': 'Chat Embeddings',
                        'db_table': 'landscape"."landscaper_chat_embedding',
                    },
                ),
            ],
        ),

        # ── ActivityItem ────────────────────────────────────────────
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS landscape.landscaper_activity (
                    activity_id SERIAL PRIMARY KEY,
                    project_id INTEGER NOT NULL REFERENCES landscape.tbl_project(project_id) ON DELETE CASCADE,
                    activity_type VARCHAR(20) NOT NULL
                        CHECK (activity_type IN ('status','decision','update','alert')),
                    title VARCHAR(100) NOT NULL,
                    summary TEXT NOT NULL,
                    status VARCHAR(20) NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('complete','partial','blocked','pending')),
                    confidence VARCHAR(20)
                        CHECK (confidence IN ('high','medium','low') OR confidence IS NULL),
                    link VARCHAR(255),
                    blocked_by TEXT,
                    details JSONB,
                    highlight_fields JSONB,
                    is_read BOOLEAN NOT NULL DEFAULT FALSE,
                    source_type VARCHAR(50),
                    source_id VARCHAR(100),
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS landscape.landscaper_activity CASCADE;",
            state_operations=[
                migrations.CreateModel(
                    name='ActivityItem',
                    fields=[
                        ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                        ('activity_type', models.CharField(choices=[('status', 'Status'), ('decision', 'Decision'), ('update', 'Update'), ('alert', 'Alert')], help_text='Type of activity: status, decision, update, alert', max_length=20)),
                        ('title', models.CharField(help_text='Short title for the activity (e.g., "Market Analysis")', max_length=100)),
                        ('summary', models.TextField(help_text='Brief summary of the activity status')),
                        ('status', models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial'), ('blocked', 'Blocked'), ('pending', 'Pending')], default='pending', help_text='Activity status: complete, partial, blocked, pending', max_length=20)),
                        ('confidence', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), (None, 'N/A')], help_text='Confidence level for this data', max_length=20, null=True)),
                        ('link', models.CharField(blank=True, help_text='Navigation link relative to project (e.g., /market)', max_length=255, null=True)),
                        ('blocked_by', models.TextField(blank=True, help_text='What is blocking this activity', null=True)),
                        ('details', models.JSONField(blank=True, help_text='Additional details as a list of strings', null=True)),
                        ('highlight_fields', models.JSONField(blank=True, help_text='List of field names to highlight when navigating', null=True)),
                        ('is_read', models.BooleanField(default=False, help_text='Whether user has viewed this activity')),
                        ('created_at', models.DateTimeField(auto_now_add=True, help_text='When activity was created')),
                        ('updated_at', models.DateTimeField(auto_now=True, help_text='When activity was last updated')),
                        ('source_type', models.CharField(blank=True, help_text='Source of activity: document, budget, market, ai_analysis', max_length=50, null=True)),
                        ('source_id', models.CharField(blank=True, help_text='Reference ID to source record', max_length=100, null=True)),
                        ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='landscaper_activities', to='projects.project')),
                    ],
                    options={
                        'verbose_name': 'Activity Item',
                        'verbose_name_plural': 'Activity Items',
                        'db_table': 'landscape"."landscaper_activity',
                        'ordering': ['-created_at'],
                        'indexes': [models.Index(fields=['project', '-created_at'], name='landscaper__project_8a480e_idx'), models.Index(fields=['project', 'is_read'], name='landscaper__project_127687_idx'), models.Index(fields=['source_type', 'source_id'], name='landscaper__source__712230_idx')],
                    },
                ),
            ],
        ),

        # ── Indexes: ChatThread ─────────────────────────────────────
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS landscaper__project_efd964_idx ON landscape.landscaper_chat_thread (project_id);",
                    reverse_sql="DROP INDEX IF EXISTS landscape.landscaper__project_efd964_idx;",
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='chatthread',
                    index=models.Index(fields=['project'], name='landscaper__project_efd964_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS landscaper__project_317b6b_idx ON landscape.landscaper_chat_thread (project_id, page_context);",
                    reverse_sql="DROP INDEX IF EXISTS landscape.landscaper__project_317b6b_idx;",
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='chatthread',
                    index=models.Index(fields=['project', 'page_context'], name='landscaper__project_317b6b_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS landscaper__project_572cee_idx ON landscape.landscaper_chat_thread (project_id, is_active);",
                    reverse_sql="DROP INDEX IF EXISTS landscape.landscaper__project_572cee_idx;",
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='chatthread',
                    index=models.Index(fields=['project', 'is_active'], name='landscaper__project_572cee_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS landscaper__project_97dc81_idx ON landscape.landscaper_chat_thread (project_id, updated_at DESC);",
                    reverse_sql="DROP INDEX IF EXISTS landscape.landscaper__project_97dc81_idx;",
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='chatthread',
                    index=models.Index(fields=['project', '-updated_at'], name='landscaper__project_97dc81_idx'),
                ),
            ],
        ),

        # ── Unique constraint: ExtractionMapping ────────────────────
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM pg_constraint
                                WHERE conrelid = 'landscape.tbl_extraction_mapping'::regclass
                                AND conname = 'uq_extraction_mapping_doc_src_tgt'
                            ) THEN
                                ALTER TABLE landscape.tbl_extraction_mapping
                                    ADD CONSTRAINT uq_extraction_mapping_doc_src_tgt
                                    UNIQUE (document_type, source_pattern, target_table, target_field);
                            END IF;
                        END $$;
                    """,
                    reverse_sql="""
                        ALTER TABLE landscape.tbl_extraction_mapping
                            DROP CONSTRAINT IF EXISTS uq_extraction_mapping_doc_src_tgt;
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='extractionmapping',
                    unique_together={('document_type', 'source_pattern', 'target_table', 'target_field')},
                ),
            ],
        ),

        # ── Indexes: ExtractionLog ──────────────────────────────────
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS tbl_extract_mapping_819a26_idx ON landscape.tbl_extraction_log (mapping_id);",
                    reverse_sql="DROP INDEX IF EXISTS landscape.tbl_extract_mapping_819a26_idx;",
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='extractionlog',
                    index=models.Index(fields=['mapping'], name='tbl_extract_mapping_819a26_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS tbl_extract_project_45b6a5_idx ON landscape.tbl_extraction_log (project_id);",
                    reverse_sql="DROP INDEX IF EXISTS landscape.tbl_extract_project_45b6a5_idx;",
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='extractionlog',
                    index=models.Index(fields=['project'], name='tbl_extract_project_45b6a5_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS tbl_extract_doc_id_4191e3_idx ON landscape.tbl_extraction_log (doc_id);",
                    reverse_sql="DROP INDEX IF EXISTS landscape.tbl_extract_doc_id_4191e3_idx;",
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='extractionlog',
                    index=models.Index(fields=['doc_id'], name='tbl_extract_doc_id_4191e3_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS tbl_extract_extract_f31dcd_idx ON landscape.tbl_extraction_log (extracted_at);",
                    reverse_sql="DROP INDEX IF EXISTS landscape.tbl_extract_extract_f31dcd_idx;",
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='extractionlog',
                    index=models.Index(fields=['extracted_at'], name='tbl_extract_extract_f31dcd_idx'),
                ),
            ],
        ),

        # ── Indexes: ThreadMessage ──────────────────────────────────
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS landscaper__thread__001166_idx ON landscape.landscaper_thread_message (thread_id);",
                    reverse_sql="DROP INDEX IF EXISTS landscape.landscaper__thread__001166_idx;",
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='threadmessage',
                    index=models.Index(fields=['thread'], name='landscaper__thread__001166_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS landscaper__thread__ae4edd_idx ON landscape.landscaper_thread_message (thread_id, created_at);",
                    reverse_sql="DROP INDEX IF EXISTS landscape.landscaper__thread__ae4edd_idx;",
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='threadmessage',
                    index=models.Index(fields=['thread', 'created_at'], name='landscaper__thread__ae4edd_idx'),
                ),
            ],
        ),

        # ── Indexes: ChatEmbedding ──────────────────────────────────
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS landscaper__project_b24d76_idx ON landscape.landscaper_chat_embedding (project_id);",
                    reverse_sql="DROP INDEX IF EXISTS landscape.landscaper__project_b24d76_idx;",
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='chatembedding',
                    index=models.Index(fields=['project_id'], name='landscaper__project_b24d76_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS landscaper__thread__a4bf47_idx ON landscape.landscaper_chat_embedding (thread_id);",
                    reverse_sql="DROP INDEX IF EXISTS landscape.landscaper__thread__a4bf47_idx;",
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='chatembedding',
                    index=models.Index(fields=['thread'], name='landscaper__thread__a4bf47_idx'),
                ),
            ],
        ),

        # ── Indexes: ActivityItem (from Meta.indexes — already in state via CreateModel) ───
        # These 3 indexes are defined in ActivityItem's Meta.indexes and already registered
        # in Django state via the CreateModel state_operations above. We only need the DB ops.
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS landscaper__project_8a480e_idx ON landscape.landscaper_activity (project_id, created_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS landscape.landscaper__project_8a480e_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS landscaper__project_127687_idx ON landscape.landscaper_activity (project_id, is_read);",
            reverse_sql="DROP INDEX IF EXISTS landscape.landscaper__project_127687_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS landscaper__source__712230_idx ON landscape.landscaper_activity (source_type, source_id);",
            reverse_sql="DROP INDEX IF EXISTS landscape.landscaper__source__712230_idx;",
        ),
    ]
