# Generated by Django 5.0.1 on 2025-11-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        help_text="Display name for this report template",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of what this report includes",
                        null=True,
                    ),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("powerpoint", "PowerPoint"),
                        ],
                        default="pdf",
                        help_text="Output file format for generated reports",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_tabs",
                    models.JSONField(
                        default=list,
                        help_text="List of tab names where this report's export button should appear",
                    ),
                ),
                (
                    "sections",
                    models.JSONField(
                        default=list,
                        help_text="List of section names to include in the generated report",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active templates appear in export dropdowns",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.TextField(
                        blank=True,
                        help_text="User who created this template",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": 'landscape"."report_templates',
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["is_active"], name="idx_report_active")
                ],
            },
        ),
    ]
