# Generated by Django 5.0.1 on 2026-01-22 19:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NarrativeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(db_column='project_id')),
                ('approach_type', models.CharField(choices=[('sales_comparison', 'Sales Comparison'), ('cost', 'Cost Approach'), ('income', 'Income Approach'), ('reconciliation', 'Reconciliation')], max_length=50)),
                ('version_number', models.IntegerField()),
                ('content', models.JSONField(help_text='TipTap JSON document')),
                ('content_html', models.TextField(blank=True, help_text='Rendered HTML for display/export', null=True)),
                ('content_plain', models.TextField(blank=True, help_text='Plain text for search/export', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('final', 'Final')], default='draft', max_length=20)),
                ('created_by', models.IntegerField(blank=True, help_text='User ID (future FK)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_narrative_version',
                'ordering': ['-version_number'],
                'managed': True,
                'unique_together': {('project_id', 'approach_type', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='NarrativeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('position_start', models.IntegerField(help_text='Character position start in document')),
                ('position_end', models.IntegerField(help_text='Character position end in document')),
                ('is_question', models.BooleanField(default=False, help_text='True if ends with ?')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_by', models.IntegerField(blank=True, help_text='User ID (future FK)', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('landscaper_response', models.TextField(blank=True, help_text='AI response to question', null=True)),
                ('created_by', models.IntegerField(blank=True, help_text='User ID (future FK)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.ForeignKey(db_column='version_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='valuation.narrativeversion')),
            ],
            options={
                'db_table': 'tbl_narrative_comment',
                'ordering': ['position_start'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NarrativeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('addition', 'Addition'), ('deletion', 'Deletion')], max_length=20)),
                ('original_text', models.TextField(blank=True, help_text='Original text (for deletions)', null=True)),
                ('new_text', models.TextField(blank=True, help_text='New text (for additions)', null=True)),
                ('position_start', models.IntegerField()),
                ('position_end', models.IntegerField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.ForeignKey(db_column='version_id', on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='valuation.narrativeversion')),
            ],
            options={
                'db_table': 'tbl_narrative_change',
                'ordering': ['position_start'],
                'managed': True,
            },
        ),
    ]
