# Generated by Django 5.0.1 on 2026-01-27 15:45
# Modified: Removed ContainerCostMetadata as tbl_container doesn't exist yet

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0001_initial'),
        ('projects', '0004_add_rbac_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandComparable',
            fields=[
                ('land_comparable_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_number', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('land_area_sf', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('land_area_acres', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_per_sf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_acre', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('zoning', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(
                    db_column='project_id',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='land_comparables',
                    to='projects.project'
                )),
            ],
            options={
                'db_table': 'tbl_land_comparables',
                'ordering': ['project', 'comp_number'],
            },
        ),
        migrations.CreateModel(
            name='LandCompAdjustment',
            fields=[
                ('adjustment_id', models.AutoField(primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[
                    ('location', 'Location'),
                    ('size', 'Size'),
                    ('condition', 'Condition'),
                    ('zoning', 'Zoning'),
                    ('other', 'Other'),
                ], max_length=50)),
                ('adjustment_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('adjustment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('land_comparable', models.ForeignKey(
                    db_column='land_comparable_id',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='adjustments',
                    to='valuation.landcomparable'
                )),
            ],
            options={
                'db_table': 'tbl_land_comp_adjustments',
                'ordering': ['land_comparable', 'adjustment_type'],
            },
        ),
        # NOTE: ContainerCostMetadata removed - tbl_container doesn't exist yet.
        # Will be added in a future migration when the container system is fully implemented.
        migrations.CreateModel(
            name='CostApproachDepreciation',
            fields=[
                ('depreciation_id', models.AutoField(primary_key=True, serialize=False)),
                ('physical_curable', models.DecimalField(default=0, decimal_places=2, max_digits=12)),
                ('physical_incurable_short', models.DecimalField(default=0, decimal_places=2, max_digits=12)),
                ('physical_incurable_long', models.DecimalField(default=0, decimal_places=2, max_digits=12)),
                ('functional_curable', models.DecimalField(default=0, decimal_places=2, max_digits=12)),
                ('functional_incurable', models.DecimalField(default=0, decimal_places=2, max_digits=12)),
                ('external_obsolescence', models.DecimalField(default=0, decimal_places=2, max_digits=12)),
                ('effective_age_years', models.IntegerField(blank=True, null=True)),
                ('remaining_life_years', models.IntegerField(blank=True, null=True)),
                ('depreciation_method', models.CharField(blank=True, choices=[
                    ('age-life', 'Age-Life'),
                    ('breakdown', 'Breakdown'),
                    ('market_extraction', 'Market Extraction'),
                    ('other', 'Other'),
                ], max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(
                    db_column='project_id',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='cost_approach_depreciation',
                    to='projects.project'
                )),
            ],
            options={
                'db_table': 'tbl_cost_approach_depreciation',
            },
        ),
    ]
