'use client';

import React, { useState, useRef, useEffect } from 'react';

interface GuidePrintButtonProps {
  chapterTitle: string;
  chapterId: string;
}

/**
 * GuidePrintButton
 *
 * Downloads pre-generated PDF for the current chapter or full guide.
 * PDFs are generated by scripts/guide/generate_pdf.py (reportlab).
 */
export default function GuidePrintButton({ chapterTitle, chapterId }: GuidePrintButtonProps) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  // Close dropdown on outside click
  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [open]);

  const downloadPdf = (url: string) => {
    setOpen(false);
    const a = document.createElement('a');
    a.href = url;
    a.download = '';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  return (
    <div ref={ref} style={{ position: 'relative', display: 'inline-block' }}>
      <button
        onClick={() => setOpen(prev => !prev)}
        className="guide-print-btn"
        style={{
          display: 'inline-flex',
          alignItems: 'center',
          gap: '0.4rem',
          padding: '0.4rem 0.85rem',
          fontSize: '0.8rem',
          border: '1px solid var(--cui-border-color)',
          borderRadius: '4px',
          backgroundColor: 'var(--cui-secondary-bg)',
          color: 'var(--cui-body-color)',
          cursor: 'pointer',
          transition: 'background-color 0.15s',
        }}
        title="Export as PDF"
      >
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M6 9V2h12v7" />
          <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" />
          <rect x="6" y="14" width="12" height="8" />
        </svg>
        Export PDF
        <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
          <path d="M6 9l6 6 6-6" />
        </svg>
      </button>

      {open && (
        <div
          style={{
            position: 'absolute',
            right: 0,
            top: '100%',
            marginTop: '4px',
            minWidth: '200px',
            backgroundColor: 'var(--cui-body-bg)',
            border: '1px solid var(--cui-border-color)',
            borderRadius: '6px',
            boxShadow: '0 4px 12px rgba(0,0,0,0.12)',
            zIndex: 50,
            overflow: 'hidden',
          }}
        >
          <button
            onClick={() => downloadPdf(`/guide/Landscape_User_Guide_Ch${chapterId}.pdf`)}
            style={{
              display: 'block',
              width: '100%',
              padding: '0.55rem 0.85rem',
              fontSize: '0.8rem',
              textAlign: 'left',
              border: 'none',
              backgroundColor: 'transparent',
              color: 'var(--cui-body-color)',
              cursor: 'pointer',
            }}
            onMouseEnter={e => (e.currentTarget.style.backgroundColor = 'var(--cui-tertiary-bg)')}
            onMouseLeave={e => (e.currentTarget.style.backgroundColor = 'transparent')}
          >
            This chapter
            <span style={{ display: 'block', fontSize: '0.7rem', color: 'var(--cui-secondary-color)', marginTop: '1px' }}>
              {chapterTitle}
            </span>
          </button>
          <div style={{ borderTop: '1px solid var(--cui-border-color)' }} />
          <button
            onClick={() => downloadPdf('/guide/Landscape_User_Guide.pdf')}
            style={{
              display: 'block',
              width: '100%',
              padding: '0.55rem 0.85rem',
              fontSize: '0.8rem',
              textAlign: 'left',
              border: 'none',
              backgroundColor: 'transparent',
              color: 'var(--cui-body-color)',
              cursor: 'pointer',
            }}
            onMouseEnter={e => (e.currentTarget.style.backgroundColor = 'var(--cui-tertiary-bg)')}
            onMouseLeave={e => (e.currentTarget.style.backgroundColor = 'transparent')}
          >
            Full guide
            <span style={{ display: 'block', fontSize: '0.7rem', color: 'var(--cui-secondary-color)', marginTop: '1px' }}>
              All chapters (PDF)
            </span>
          </button>
        </div>
      )}
    </div>
  );
}
