# Generated by Django 5.0.1 on 2025-11-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add product_code and growth_rate fields to land_use_pricing table
    to support product-specific pricing assumptions.
    """
    dependencies = []

    operations = [
        migrations.RunSQL(
            # Add product_code column
            sql="""
                ALTER TABLE landscape.land_use_pricing
                ADD COLUMN IF NOT EXISTS product_code VARCHAR(100);
            """,
            reverse_sql="""
                ALTER TABLE landscape.land_use_pricing
                DROP COLUMN IF EXISTS product_code;
            """
        ),
        migrations.RunSQL(
            # Add growth_rate column (replaces inflation_type with numeric rate)
            sql="""
                ALTER TABLE landscape.land_use_pricing
                ADD COLUMN IF NOT EXISTS growth_rate DECIMAL(5,4);
            """,
            reverse_sql="""
                ALTER TABLE landscape.land_use_pricing
                DROP COLUMN IF EXISTS growth_rate;
            """
        ),
        migrations.RunSQL(
            # Drop old unique constraint
            sql="""
                ALTER TABLE landscape.land_use_pricing
                DROP CONSTRAINT IF EXISTS land_use_pricing_project_id_lu_type_code_key;
            """,
            reverse_sql="""
                ALTER TABLE landscape.land_use_pricing
                ADD CONSTRAINT land_use_pricing_project_id_lu_type_code_key
                UNIQUE (project_id, lu_type_code);
            """
        ),
        migrations.RunSQL(
            # Add new unique constraint including product_code
            sql="""
                ALTER TABLE landscape.land_use_pricing
                ADD CONSTRAINT land_use_pricing_project_type_product_key
                UNIQUE (project_id, lu_type_code, product_code);
            """,
            reverse_sql="""
                ALTER TABLE landscape.land_use_pricing
                DROP CONSTRAINT IF EXISTS land_use_pricing_project_type_product_key;
            """
        ),
    ]
